ALTER TABLE [dbo].[Articulos] DROP CONSTRAINT [CHK_ART_IVA]
GO

ALTER TABLE [dbo].[Articulos] DROP CONSTRAINT [CHK_ART_IEPS]
GO

ALTER TABLE [dbo].[Articulos] WITH CHECK ADD CONSTRAINT [CHK_ART_IVA] CHECK ([ART_IVA] >= 0 AND [ART_IVA] <= 1)
GO

ALTER TABLE [dbo].[Articulos] WITH CHECK ADD CONSTRAINT [CHK_ART_IEPS] CHECK ([ART_IEPS] >= 0 AND [ART_IEPS] <= 1)
GO

ALTER TABLE [dbo].[OrdenesCompra] WITH CHECK ADD CONSTRAINT [CHK_OC_Descuento] CHECK ([OC_Descuento] >= 0 AND [OC_Descuento] <= 1)
GO

ALTER TABLE [dbo].[OrdenesCompraDetalles] WITH CHECK ADD CONSTRAINT [CHK_OCD_IVA] CHECK ([OCD_IVA] >= 0 AND [OCD_IVA] <= 1)
GO

ALTER TABLE [dbo].[OrdenesCompraDetalles] WITH CHECK ADD CONSTRAINT [CHK_OCD_IEPS] CHECK ([OCD_IEPS] >= 0 AND [OCD_IEPS] <= 1)
GO