UPDATE CXPFacturasDetalles SET
	CXPFD_IVA = CASE WHEN CXPSPSD_CXPSolicitudPagoServicioDetalleId IS NULL THEN CXPFD_IVA ELSE 0 END,
	CXPFD_IVAExento = CASE WHEN CXPSPSD_CXPSolicitudPagoServicioDetalleId IS NULL THEN CXPFD_IVAExento ELSE 0 END,
	CXPFD_IEPS = CASE WHEN CXPSPSD_CXPSolicitudPagoServicioDetalleId IS NULL THEN CXPFD_IEPS ELSE 0 END,
	CXPFD_IEPSCuotaFija = CASE WHEN CXPSPSD_CXPSolicitudPagoServicioDetalleId IS NULL THEN CXPFD_IEPSCuotaFija ELSE NULL END,
	CXPFD_Descuento = CASE WHEN CXPSPSD_CXPSolicitudPagoServicioDetalleId IS NULL THEN CXPFD_Descuento ELSE 0 END,
	CXPFD_CMM_TipoRetencionId = CASE WHEN CXPSPSD_CXPSolicitudPagoServicioDetalleId IS NULL THEN CXPFD_CMM_TipoRetencionId ELSE NULL END
FROM CXPFacturasDetalles
LEFT JOIN CXPSolicitudesPagosServiciosDetalles ON CXPSPSD_CXPF_CXPFacturaId = CXPFD_CXPF_CXPFacturaId
GO