ALTER TABLE CXCFacturas ADD CXCF_XML XML NULL
GO

ALTER TABLE CXCFacturas DROP CONSTRAINT FK_CXCFacturas_FacturaXMLId
GO

ALTER TABLE CXCFacturas DROP CONSTRAINT FK_CXCFacturas_FacturaPDFId
GO

ALTER TABLE CXCFacturas DROP COLUMN CXCF_ARC_FacturaXMLId
GO

ALTER TABLE CXCFacturas DROP COLUMN CXCF_ARC_FacturaPDFId
GO