ALTER TABLE Bancos ADD BAN_Codigo VARCHAR(3) NULL
GO

ALTER TABLE Bancos ADD BAN_RFC VARCHAR(20) NULL
GO

ALTER TABLE Bancos ADD BAN_RazonSocial VARCHAR(200) NULL
GO

UPDATE Bancos SET BAN_Codigo = '', BAN_RFC = '', BAN_RazonSocial = ''
GO

ALTER TABLE Bancos ALTER COLUMN BAN_Codigo VARCHAR(3) NOT NULL
GO

ALTER TABLE Bancos ALTER COLUMN BAN_RFC VARCHAR(20) NOT NULL
GO

ALTER TABLE Bancos ALTER COLUMN BAN_RazonSocial VARCHAR(200) NOT NULL
GO