UPDATE [dbo].[BecasUDG]
	SET [BECU_ENBE_EntidadBecaId] = (CASE WHEN [NOMBREDESCUENTOUDG] LIKE '%STAUDG%' THEN 2 ELSE 1 END)
FROM
	[dbo].[BecasUDG]
	INNER JOIN [dbo].[BECAS_ALUMNOS_RH] ON [BECU_SIAPId] = [ID]
WHERE 
	[BECU_ENBE_EntidadBecaId] IS NULL
GO