UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 4565 WHERE ALUG_AlumnoGrupoId = 1161
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15995 WHERE ALUG_AlumnoGrupoId = 14961
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 4151 WHERE ALUG_AlumnoGrupoId = 14584
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 25798 WHERE ALUG_AlumnoGrupoId = 25303
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 10464 WHERE ALUG_AlumnoGrupoId = 9491
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19588 WHERE ALUG_AlumnoGrupoId = 18540
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29132 WHERE ALUG_AlumnoGrupoId = 28716
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14573 WHERE ALUG_AlumnoGrupoId = 13541
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 16042 WHERE ALUG_AlumnoGrupoId = 15008
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 21751 WHERE ALUG_AlumnoGrupoId = 21196
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 2747 WHERE ALUG_AlumnoGrupoId = 7123
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 21996 WHERE ALUG_AlumnoGrupoId = 21441
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 23826 WHERE ALUG_AlumnoGrupoId = 23277
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29318 WHERE ALUG_AlumnoGrupoId = 28902
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14568 WHERE ALUG_AlumnoGrupoId = 13536
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19126 WHERE ALUG_AlumnoGrupoId = 18079
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19442 WHERE ALUG_AlumnoGrupoId = 18394
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 27132 WHERE ALUG_AlumnoGrupoId = 26637
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19751 WHERE ALUG_AlumnoGrupoId = 18703
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 18981 WHERE ALUG_AlumnoGrupoId = 17934
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29203 WHERE ALUG_AlumnoGrupoId = 28787
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 28731 WHERE ALUG_AlumnoGrupoId = 28256
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 16043 WHERE ALUG_AlumnoGrupoId = 15009
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 23805 WHERE ALUG_AlumnoGrupoId = 23256
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 8792 WHERE ALUG_AlumnoGrupoId = 3044
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29179 WHERE ALUG_AlumnoGrupoId = 28763
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 13129 WHERE ALUG_AlumnoGrupoId = 12110
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 1666 WHERE ALUG_AlumnoGrupoId = 8425
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19666 WHERE ALUG_AlumnoGrupoId = 18618
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 21734 WHERE ALUG_AlumnoGrupoId = 21179
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 9346 WHERE ALUG_AlumnoGrupoId = 3971
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 17109 WHERE ALUG_AlumnoGrupoId = 16071
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 4444 WHERE ALUG_AlumnoGrupoId = 2018
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14654 WHERE ALUG_AlumnoGrupoId = 29160
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14594 WHERE ALUG_AlumnoGrupoId = 13562
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 26660 WHERE ALUG_AlumnoGrupoId = 26165
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29133 WHERE ALUG_AlumnoGrupoId = 28717
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14595 WHERE ALUG_AlumnoGrupoId = 13563
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14966 WHERE ALUG_AlumnoGrupoId = 13934
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 17617 WHERE ALUG_AlumnoGrupoId = 16575
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 3443 WHERE ALUG_AlumnoGrupoId = 2965
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14198 WHERE ALUG_AlumnoGrupoId = 13167
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 18324 WHERE ALUG_AlumnoGrupoId = 17280
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 10812 WHERE ALUG_AlumnoGrupoId = 9831
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 3637 WHERE ALUG_AlumnoGrupoId = 7739
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29180 WHERE ALUG_AlumnoGrupoId = 28764
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 2656 WHERE ALUG_AlumnoGrupoId = 6893
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15115 WHERE ALUG_AlumnoGrupoId = 14083
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 3586 WHERE ALUG_AlumnoGrupoId = 6723
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 11611 WHERE ALUG_AlumnoGrupoId = 10604
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29181 WHERE ALUG_AlumnoGrupoId = 28765
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29225 WHERE ALUG_AlumnoGrupoId = 28809
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15996 WHERE ALUG_AlumnoGrupoId = 14962
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12804 WHERE ALUG_AlumnoGrupoId = 11785
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 11697 WHERE ALUG_AlumnoGrupoId = 10690
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 27001 WHERE ALUG_AlumnoGrupoId = 26506
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29155 WHERE ALUG_AlumnoGrupoId = 28739
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 13021 WHERE ALUG_AlumnoGrupoId = 12002
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29226 WHERE ALUG_AlumnoGrupoId = 28810
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20116 WHERE ALUG_AlumnoGrupoId = 28907
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20010 WHERE ALUG_AlumnoGrupoId = 18961
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 4345 WHERE ALUG_AlumnoGrupoId = 4706
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20455 WHERE ALUG_AlumnoGrupoId = 19406
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15029 WHERE ALUG_AlumnoGrupoId = 13997
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 4494 WHERE ALUG_AlumnoGrupoId = 2540
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 4346 WHERE ALUG_AlumnoGrupoId = 2060
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19101 WHERE ALUG_AlumnoGrupoId = 18054
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12805 WHERE ALUG_AlumnoGrupoId = 11786
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 3283 WHERE ALUG_AlumnoGrupoId = 2603
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 1113 WHERE ALUG_AlumnoGrupoId = 970
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14445 WHERE ALUG_AlumnoGrupoId = 13414
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12503 WHERE ALUG_AlumnoGrupoId = 11486
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 10392 WHERE ALUG_AlumnoGrupoId = 9421
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 9393 WHERE ALUG_AlumnoGrupoId = 3799
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 3857 WHERE ALUG_AlumnoGrupoId = 1964
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 21061 WHERE ALUG_AlumnoGrupoId = 20005
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12526 WHERE ALUG_AlumnoGrupoId = 11509
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 10268 WHERE ALUG_AlumnoGrupoId = 9299
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12525 WHERE ALUG_AlumnoGrupoId = 11508
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12091 WHERE ALUG_AlumnoGrupoId = 11075
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20453 WHERE ALUG_AlumnoGrupoId = 19404
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20226 WHERE ALUG_AlumnoGrupoId = 19177
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 9140 WHERE ALUG_AlumnoGrupoId = 4208
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 18982 WHERE ALUG_AlumnoGrupoId = 17935
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19668 WHERE ALUG_AlumnoGrupoId = 18620
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12527 WHERE ALUG_AlumnoGrupoId = 11510
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19081 WHERE ALUG_AlumnoGrupoId = 18034
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 17110 WHERE ALUG_AlumnoGrupoId = 16072
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14695 WHERE ALUG_AlumnoGrupoId = 13663
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29134 WHERE ALUG_AlumnoGrupoId = 28718
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14608 WHERE ALUG_AlumnoGrupoId = 13576
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 25968 WHERE ALUG_AlumnoGrupoId = 25473
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14578 WHERE ALUG_AlumnoGrupoId = 13546
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14566 WHERE ALUG_AlumnoGrupoId = 13534
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 10814 WHERE ALUG_AlumnoGrupoId = 9833
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 21098 WHERE ALUG_AlumnoGrupoId = 20042
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 11864 WHERE ALUG_AlumnoGrupoId = 10853
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 2657 WHERE ALUG_AlumnoGrupoId = 8484
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 27003 WHERE ALUG_AlumnoGrupoId = 26508
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 13311 WHERE ALUG_AlumnoGrupoId = 12292
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 11743 WHERE ALUG_AlumnoGrupoId = 10734
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 10222 WHERE ALUG_AlumnoGrupoId = 9254
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 21735 WHERE ALUG_AlumnoGrupoId = 21180
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20766 WHERE ALUG_AlumnoGrupoId = 19713
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 17021 WHERE ALUG_AlumnoGrupoId = 15984
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29204 WHERE ALUG_AlumnoGrupoId = 28788
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 21736 WHERE ALUG_AlumnoGrupoId = 21181
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20816 WHERE ALUG_AlumnoGrupoId = 19763
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15443 WHERE ALUG_AlumnoGrupoId = 14411
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20948 WHERE ALUG_AlumnoGrupoId = 19893
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 28574 WHERE ALUG_AlumnoGrupoId = 28099
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19445 WHERE ALUG_AlumnoGrupoId = 18397
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20623 WHERE ALUG_AlumnoGrupoId = 19574
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 21737 WHERE ALUG_AlumnoGrupoId = 21182
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19129 WHERE ALUG_AlumnoGrupoId = 18082
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 1937 WHERE ALUG_AlumnoGrupoId = 4684
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29182 WHERE ALUG_AlumnoGrupoId = 28766
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 17975 WHERE ALUG_AlumnoGrupoId = 16932
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 16625 WHERE ALUG_AlumnoGrupoId = 15591
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12391 WHERE ALUG_AlumnoGrupoId = 11375
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19919 WHERE ALUG_AlumnoGrupoId = 18870
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19570 WHERE ALUG_AlumnoGrupoId = 18522
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15465 WHERE ALUG_AlumnoGrupoId = 14433
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12840 WHERE ALUG_AlumnoGrupoId = 11821
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20719 WHERE ALUG_AlumnoGrupoId = 19667
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 16522 WHERE ALUG_AlumnoGrupoId = 15488
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 17167 WHERE ALUG_AlumnoGrupoId = 16128
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29183 WHERE ALUG_AlumnoGrupoId = 28767
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 16626 WHERE ALUG_AlumnoGrupoId = 15592
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12528 WHERE ALUG_AlumnoGrupoId = 11511
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20959 WHERE ALUG_AlumnoGrupoId = 19903
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29227 WHERE ALUG_AlumnoGrupoId = 28811
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 10790 WHERE ALUG_AlumnoGrupoId = 20594
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 24949 WHERE ALUG_AlumnoGrupoId = 24430
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19985 WHERE ALUG_AlumnoGrupoId = 18936
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29156 WHERE ALUG_AlumnoGrupoId = 28740
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 2704 WHERE ALUG_AlumnoGrupoId = 8249
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 6686 WHERE ALUG_AlumnoGrupoId = 6418
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 18984 WHERE ALUG_AlumnoGrupoId = 17937
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29184 WHERE ALUG_AlumnoGrupoId = 28768
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 18306 WHERE ALUG_AlumnoGrupoId = 17262
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 10073 WHERE ALUG_AlumnoGrupoId = 9107
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 23314 WHERE ALUG_AlumnoGrupoId = 22763
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 18247 WHERE ALUG_AlumnoGrupoId = 17204
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 18282 WHERE ALUG_AlumnoGrupoId = 17238
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 10513 WHERE ALUG_AlumnoGrupoId = 9540
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 10445 WHERE ALUG_AlumnoGrupoId = 9472
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12074 WHERE ALUG_AlumnoGrupoId = 11058
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 18329 WHERE ALUG_AlumnoGrupoId = 17285
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20012 WHERE ALUG_AlumnoGrupoId = 18963
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 10768 WHERE ALUG_AlumnoGrupoId = 9788
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 8091 WHERE ALUG_AlumnoGrupoId = 1928
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20480 WHERE ALUG_AlumnoGrupoId = 19431
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14571 WHERE ALUG_AlumnoGrupoId = 13539
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 11885 WHERE ALUG_AlumnoGrupoId = 10873
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20701 WHERE ALUG_AlumnoGrupoId = 19649
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 1646 WHERE ALUG_AlumnoGrupoId = 11746
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12765 WHERE ALUG_AlumnoGrupoId = 28631
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 2582 WHERE ALUG_AlumnoGrupoId = 3397
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15295 WHERE ALUG_AlumnoGrupoId = 14263
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 17113 WHERE ALUG_AlumnoGrupoId = 16075
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 27000 WHERE ALUG_AlumnoGrupoId = 26505
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15488 WHERE ALUG_AlumnoGrupoId = 14456
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 4138 WHERE ALUG_AlumnoGrupoId = 8730
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29714 WHERE ALUG_AlumnoGrupoId = 29725
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 30033 WHERE ALUG_AlumnoGrupoId = 29725
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 21738 WHERE ALUG_AlumnoGrupoId = 21183
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 2659 WHERE ALUG_AlumnoGrupoId = 4671
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 22019 WHERE ALUG_AlumnoGrupoId = 21464
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19986 WHERE ALUG_AlumnoGrupoId = 18937
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 11766 WHERE ALUG_AlumnoGrupoId = 10757
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 21063 WHERE ALUG_AlumnoGrupoId = 20007
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 13527 WHERE ALUG_AlumnoGrupoId = 12508
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 4598 WHERE ALUG_AlumnoGrupoId = 8092
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14123 WHERE ALUG_AlumnoGrupoId = 13092
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20788 WHERE ALUG_AlumnoGrupoId = 19735
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 10248 WHERE ALUG_AlumnoGrupoId = 9279
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 18233 WHERE ALUG_AlumnoGrupoId = 17190
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 18893 WHERE ALUG_AlumnoGrupoId = 17847
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29185 WHERE ALUG_AlumnoGrupoId = 28769
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 17397 WHERE ALUG_AlumnoGrupoId = 16358
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19987 WHERE ALUG_AlumnoGrupoId = 18938
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15935 WHERE ALUG_AlumnoGrupoId = 14902
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 23557 WHERE ALUG_AlumnoGrupoId = 23008
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 18934 WHERE ALUG_AlumnoGrupoId = 17888
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14596 WHERE ALUG_AlumnoGrupoId = 13564
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29242 WHERE ALUG_AlumnoGrupoId = 28826
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 1031 WHERE ALUG_AlumnoGrupoId = 1992
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20839 WHERE ALUG_AlumnoGrupoId = 19786
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20704 WHERE ALUG_AlumnoGrupoId = 19652
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 3641 WHERE ALUG_AlumnoGrupoId = 3214
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 11617 WHERE ALUG_AlumnoGrupoId = 10610
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12970 WHERE ALUG_AlumnoGrupoId = 11951
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 18988 WHERE ALUG_AlumnoGrupoId = 17941
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19988 WHERE ALUG_AlumnoGrupoId = 18939
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20448 WHERE ALUG_AlumnoGrupoId = 19399
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 28573 WHERE ALUG_AlumnoGrupoId = 28098
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 514 WHERE ALUG_AlumnoGrupoId = 4338
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29206 WHERE ALUG_AlumnoGrupoId = 28790
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29205 WHERE ALUG_AlumnoGrupoId = 28789
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29207 WHERE ALUG_AlumnoGrupoId = 28791
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15853 WHERE ALUG_AlumnoGrupoId = 14820
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 13974 WHERE ALUG_AlumnoGrupoId = 12943
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 27002 WHERE ALUG_AlumnoGrupoId = 26507
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 17041 WHERE ALUG_AlumnoGrupoId = 16004
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19450 WHERE ALUG_AlumnoGrupoId = 18402
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29208 WHERE ALUG_AlumnoGrupoId = 28792
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29186 WHERE ALUG_AlumnoGrupoId = 28770
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 2635 WHERE ALUG_AlumnoGrupoId = 6407
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 17132 WHERE ALUG_AlumnoGrupoId = 16093
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 21162 WHERE ALUG_AlumnoGrupoId = 20530
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20864 WHERE ALUG_AlumnoGrupoId = 19811
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15936 WHERE ALUG_AlumnoGrupoId = 14903
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 10772 WHERE ALUG_AlumnoGrupoId = 9792
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 4599 WHERE ALUG_AlumnoGrupoId = 795
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 18116 WHERE ALUG_AlumnoGrupoId = 17073
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12329 WHERE ALUG_AlumnoGrupoId = 11313
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 2706 WHERE ALUG_AlumnoGrupoId = 871
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19473 WHERE ALUG_AlumnoGrupoId = 18425
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 8583 WHERE ALUG_AlumnoGrupoId = 4067
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 13202 WHERE ALUG_AlumnoGrupoId = 12183
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15035 WHERE ALUG_AlumnoGrupoId = 14003
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20473 WHERE ALUG_AlumnoGrupoId = 19424
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 3663 WHERE ALUG_AlumnoGrupoId = 8742
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15793 WHERE ALUG_AlumnoGrupoId = 3803
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 10417 WHERE ALUG_AlumnoGrupoId = 9445
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15489 WHERE ALUG_AlumnoGrupoId = 14457
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29244 WHERE ALUG_AlumnoGrupoId = 28828
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29175 WHERE ALUG_AlumnoGrupoId = 28759
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 10019 WHERE ALUG_AlumnoGrupoId = 9054
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 26477 WHERE ALUG_AlumnoGrupoId = 25982
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12330 WHERE ALUG_AlumnoGrupoId = 11314
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20156 WHERE ALUG_AlumnoGrupoId = 19107
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 4139 WHERE ALUG_AlumnoGrupoId = 4504
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14855 WHERE ALUG_AlumnoGrupoId = 13823
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20484 WHERE ALUG_AlumnoGrupoId = 19435
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 16330 WHERE ALUG_AlumnoGrupoId = 15296
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 3066 WHERE ALUG_AlumnoGrupoId = 210
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 16834 WHERE ALUG_AlumnoGrupoId = 15799
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 28672 WHERE ALUG_AlumnoGrupoId = 28197
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29331 WHERE ALUG_AlumnoGrupoId = 29015
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12397 WHERE ALUG_AlumnoGrupoId = 11381
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12573 WHERE ALUG_AlumnoGrupoId = 11556
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 21938 WHERE ALUG_AlumnoGrupoId = 21383
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 3421 WHERE ALUG_AlumnoGrupoId = 3293
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19770 WHERE ALUG_AlumnoGrupoId = 18721
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 21858 WHERE ALUG_AlumnoGrupoId = 21303
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12093 WHERE ALUG_AlumnoGrupoId = 11077
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 421 WHERE ALUG_AlumnoGrupoId = 4592
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 4022 WHERE ALUG_AlumnoGrupoId = 4555
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 8813 WHERE ALUG_AlumnoGrupoId = 1255
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 10041 WHERE ALUG_AlumnoGrupoId = 9075
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15192 WHERE ALUG_AlumnoGrupoId = 14160
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 28859 WHERE ALUG_AlumnoGrupoId = 28384
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12644 WHERE ALUG_AlumnoGrupoId = 11627
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14574 WHERE ALUG_AlumnoGrupoId = 13542
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14567 WHERE ALUG_AlumnoGrupoId = 13535
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 6464 WHERE ALUG_AlumnoGrupoId = 5535
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 16699 WHERE ALUG_AlumnoGrupoId = 15665
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19752 WHERE ALUG_AlumnoGrupoId = 18704
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 18755 WHERE ALUG_AlumnoGrupoId = 17709
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29209 WHERE ALUG_AlumnoGrupoId = 28793
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14570 WHERE ALUG_AlumnoGrupoId = 13538
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29157 WHERE ALUG_AlumnoGrupoId = 28741
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29158 WHERE ALUG_AlumnoGrupoId = 28742
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19992 WHERE ALUG_AlumnoGrupoId = 18943
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 16837 WHERE ALUG_AlumnoGrupoId = 15802
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20628 WHERE ALUG_AlumnoGrupoId = 19579
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 11815 WHERE ALUG_AlumnoGrupoId = 10805
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 21120 WHERE ALUG_AlumnoGrupoId = 20064
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20802 WHERE ALUG_AlumnoGrupoId = 19749
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20487 WHERE ALUG_AlumnoGrupoId = 19438
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29159 WHERE ALUG_AlumnoGrupoId = 28743
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 18628 WHERE ALUG_AlumnoGrupoId = 17583
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12635 WHERE ALUG_AlumnoGrupoId = 11618
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 8217 WHERE ALUG_AlumnoGrupoId = 7971
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14602 WHERE ALUG_AlumnoGrupoId = 13570
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14597 WHERE ALUG_AlumnoGrupoId = 13565
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14572 WHERE ALUG_AlumnoGrupoId = 13540
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 3476 WHERE ALUG_AlumnoGrupoId = 6269
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 17985 WHERE ALUG_AlumnoGrupoId = 16942
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 13951 WHERE ALUG_AlumnoGrupoId = 12920
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 17195 WHERE ALUG_AlumnoGrupoId = 16156
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15233 WHERE ALUG_AlumnoGrupoId = 14201
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 3361 WHERE ALUG_AlumnoGrupoId = 3254
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 24936 WHERE ALUG_AlumnoGrupoId = 24417
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 21752 WHERE ALUG_AlumnoGrupoId = 21197
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 13532 WHERE ALUG_AlumnoGrupoId = 12513
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20017 WHERE ALUG_AlumnoGrupoId = 18968
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15872 WHERE ALUG_AlumnoGrupoId = 14839
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15914 WHERE ALUG_AlumnoGrupoId = 14881
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 25893 WHERE ALUG_AlumnoGrupoId = 25398
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19622 WHERE ALUG_AlumnoGrupoId = 18574
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 21739 WHERE ALUG_AlumnoGrupoId = 21184
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 21740 WHERE ALUG_AlumnoGrupoId = 21185
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 18352 WHERE ALUG_AlumnoGrupoId = 17308
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14099 WHERE ALUG_AlumnoGrupoId = 13068
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19734 WHERE ALUG_AlumnoGrupoId = 18686
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29187 WHERE ALUG_AlumnoGrupoId = 28771
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 16528 WHERE ALUG_AlumnoGrupoId = 15494
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14609 WHERE ALUG_AlumnoGrupoId = 13577
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14575 WHERE ALUG_AlumnoGrupoId = 13543
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19043 WHERE ALUG_AlumnoGrupoId = 17996
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 11753 WHERE ALUG_AlumnoGrupoId = 10744
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29188 WHERE ALUG_AlumnoGrupoId = 28772
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20958 WHERE ALUG_AlumnoGrupoId = 19902
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 18937 WHERE ALUG_AlumnoGrupoId = 17891
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29210 WHERE ALUG_AlumnoGrupoId = 28794
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15121 WHERE ALUG_AlumnoGrupoId = 14089
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 13583 WHERE ALUG_AlumnoGrupoId = 12564
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 11789 WHERE ALUG_AlumnoGrupoId = 10779
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 27205 WHERE ALUG_AlumnoGrupoId = 26710
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19597 WHERE ALUG_AlumnoGrupoId = 18549
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 16167 WHERE ALUG_AlumnoGrupoId = 15133
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29222 WHERE ALUG_AlumnoGrupoId = 28806
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29223 WHERE ALUG_AlumnoGrupoId = 28807
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29409 WHERE ALUG_AlumnoGrupoId = 29359
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 13510 WHERE ALUG_AlumnoGrupoId = 12491
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 9414 WHERE ALUG_AlumnoGrupoId = 2973
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 21741 WHERE ALUG_AlumnoGrupoId = 21186
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14500 WHERE ALUG_AlumnoGrupoId = 13468
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19922 WHERE ALUG_AlumnoGrupoId = 18873
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 1589 WHERE ALUG_AlumnoGrupoId = 5209
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19526 WHERE ALUG_AlumnoGrupoId = 18478
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12531 WHERE ALUG_AlumnoGrupoId = 11514
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19375 WHERE ALUG_AlumnoGrupoId = 18327
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19750 WHERE ALUG_AlumnoGrupoId = 18702
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 16567 WHERE ALUG_AlumnoGrupoId = 15533
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 16217 WHERE ALUG_AlumnoGrupoId = 15183
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15964 WHERE ALUG_AlumnoGrupoId = 14931
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 10059 WHERE ALUG_AlumnoGrupoId = 9093
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19676 WHERE ALUG_AlumnoGrupoId = 18628
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15236 WHERE ALUG_AlumnoGrupoId = 14204
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19475 WHERE ALUG_AlumnoGrupoId = 18427
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 16410 WHERE ALUG_AlumnoGrupoId = 15376
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 18939 WHERE ALUG_AlumnoGrupoId = 17893
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15857 WHERE ALUG_AlumnoGrupoId = 14824
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12639 WHERE ALUG_AlumnoGrupoId = 11622
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 11768 WHERE ALUG_AlumnoGrupoId = 10759
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 11171 WHERE ALUG_AlumnoGrupoId = 10164
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15216 WHERE ALUG_AlumnoGrupoId = 14184
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14603 WHERE ALUG_AlumnoGrupoId = 13571
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 16050 WHERE ALUG_AlumnoGrupoId = 15016
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 6252 WHERE ALUG_AlumnoGrupoId = 5896
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 10234 WHERE ALUG_AlumnoGrupoId = 9266
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 25930 WHERE ALUG_AlumnoGrupoId = 25435
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20446 WHERE ALUG_AlumnoGrupoId = 19397
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 10376 WHERE ALUG_AlumnoGrupoId = 9405
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 2734 WHERE ALUG_AlumnoGrupoId = 6287
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 9220 WHERE ALUG_AlumnoGrupoId = 7196
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12987 WHERE ALUG_AlumnoGrupoId = 11968
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20058 WHERE ALUG_AlumnoGrupoId = 19009
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29211 WHERE ALUG_AlumnoGrupoId = 28795
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19924 WHERE ALUG_AlumnoGrupoId = 18875
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 23887 WHERE ALUG_AlumnoGrupoId = 23338
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 9105 WHERE ALUG_AlumnoGrupoId = 7375
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15038 WHERE ALUG_AlumnoGrupoId = 14006
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 25627 WHERE ALUG_AlumnoGrupoId = 25132
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12866 WHERE ALUG_AlumnoGrupoId = 11847
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 21742 WHERE ALUG_AlumnoGrupoId = 21187
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 11635 WHERE ALUG_AlumnoGrupoId = 10628
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19599 WHERE ALUG_AlumnoGrupoId = 18551
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 26211 WHERE ALUG_AlumnoGrupoId = 25716
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 24853 WHERE ALUG_AlumnoGrupoId = 24305
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 21743 WHERE ALUG_AlumnoGrupoId = 21188
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19700 WHERE ALUG_AlumnoGrupoId = 18652
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12576 WHERE ALUG_AlumnoGrupoId = 11559
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 10235 WHERE ALUG_AlumnoGrupoId = 9267
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20723 WHERE ALUG_AlumnoGrupoId = 19671
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14579 WHERE ALUG_AlumnoGrupoId = 13547
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29212 WHERE ALUG_AlumnoGrupoId = 28796
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 2844 WHERE ALUG_AlumnoGrupoId = 985
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 21744 WHERE ALUG_AlumnoGrupoId = 21189
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14470 WHERE ALUG_AlumnoGrupoId = 13439
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 11710 WHERE ALUG_AlumnoGrupoId = 10702
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 13290 WHERE ALUG_AlumnoGrupoId = 12271
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29160 WHERE ALUG_AlumnoGrupoId = 28744
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12532 WHERE ALUG_AlumnoGrupoId = 11515
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 4605 WHERE ALUG_AlumnoGrupoId = 1471
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29161 WHERE ALUG_AlumnoGrupoId = 28745
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 3646 WHERE ALUG_AlumnoGrupoId = 8790
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19803 WHERE ALUG_AlumnoGrupoId = 18754
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12827 WHERE ALUG_AlumnoGrupoId = 11808
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29213 WHERE ALUG_AlumnoGrupoId = 28797
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19548 WHERE ALUG_AlumnoGrupoId = 18500
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20451 WHERE ALUG_AlumnoGrupoId = 19402
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19132 WHERE ALUG_AlumnoGrupoId = 18085
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29162 WHERE ALUG_AlumnoGrupoId = 28746
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 18849 WHERE ALUG_AlumnoGrupoId = 17803
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29214 WHERE ALUG_AlumnoGrupoId = 28798
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 21014 WHERE ALUG_AlumnoGrupoId = 19958
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 18995 WHERE ALUG_AlumnoGrupoId = 17948
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29176 WHERE ALUG_AlumnoGrupoId = 28760
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19925 WHERE ALUG_AlumnoGrupoId = 18876
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14956 WHERE ALUG_AlumnoGrupoId = 13924
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 16051 WHERE ALUG_AlumnoGrupoId = 15017
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 10258 WHERE ALUG_AlumnoGrupoId = 9289
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12516 WHERE ALUG_AlumnoGrupoId = 11499
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14158 WHERE ALUG_AlumnoGrupoId = 13127
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 21155 WHERE ALUG_AlumnoGrupoId = 20523
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14284 WHERE ALUG_AlumnoGrupoId = 13253
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12794 WHERE ALUG_AlumnoGrupoId = 11775
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 17382 WHERE ALUG_AlumnoGrupoId = 16343
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14607 WHERE ALUG_AlumnoGrupoId = 13575
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19015 WHERE ALUG_AlumnoGrupoId = 17968
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 3087 WHERE ALUG_AlumnoGrupoId = 4635
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15703 WHERE ALUG_AlumnoGrupoId = 14670
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 11890 WHERE ALUG_AlumnoGrupoId = 10878
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14977 WHERE ALUG_AlumnoGrupoId = 13945
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29221 WHERE ALUG_AlumnoGrupoId = 28805
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 3368 WHERE ALUG_AlumnoGrupoId = 2214
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12472 WHERE ALUG_AlumnoGrupoId = 11456
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 11819 WHERE ALUG_AlumnoGrupoId = 10809
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15564 WHERE ALUG_AlumnoGrupoId = 14532
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20397 WHERE ALUG_AlumnoGrupoId = 19348
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 21745 WHERE ALUG_AlumnoGrupoId = 21190
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 9312 WHERE ALUG_AlumnoGrupoId = 2570
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 11949 WHERE ALUG_AlumnoGrupoId = 10936
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 10819 WHERE ALUG_AlumnoGrupoId = 9838
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15969 WHERE ALUG_AlumnoGrupoId = 22758
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 11670 WHERE ALUG_AlumnoGrupoId = 10663
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19996 WHERE ALUG_AlumnoGrupoId = 18947
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19378 WHERE ALUG_AlumnoGrupoId = 18330
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 24699 WHERE ALUG_AlumnoGrupoId = 24151
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 13050 WHERE ALUG_AlumnoGrupoId = 12031
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 10820 WHERE ALUG_AlumnoGrupoId = 9839
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 22338 WHERE ALUG_AlumnoGrupoId = 21783
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20235 WHERE ALUG_AlumnoGrupoId = 19186
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 7932 WHERE ALUG_AlumnoGrupoId = 6563
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29189 WHERE ALUG_AlumnoGrupoId = 28773
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 4405 WHERE ALUG_AlumnoGrupoId = 4695
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20021 WHERE ALUG_AlumnoGrupoId = 18972
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29215 WHERE ALUG_AlumnoGrupoId = 28799
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12408 WHERE ALUG_AlumnoGrupoId = 11392
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20997 WHERE ALUG_AlumnoGrupoId = 19941
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 21060 WHERE ALUG_AlumnoGrupoId = 20004
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 3595 WHERE ALUG_AlumnoGrupoId = 8849
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 10534 WHERE ALUG_AlumnoGrupoId = 9560
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15876 WHERE ALUG_AlumnoGrupoId = 14843
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 4354 WHERE ALUG_AlumnoGrupoId = 6695
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 24834 WHERE ALUG_AlumnoGrupoId = 24286
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14600 WHERE ALUG_AlumnoGrupoId = 13568
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12313 WHERE ALUG_AlumnoGrupoId = 11297
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 3596 WHERE ALUG_AlumnoGrupoId = 5192
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 21019 WHERE ALUG_AlumnoGrupoId = 19963
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 16395 WHERE ALUG_AlumnoGrupoId = 15361
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 24041 WHERE ALUG_AlumnoGrupoId = 23492
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 16053 WHERE ALUG_AlumnoGrupoId = 15019
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20725 WHERE ALUG_AlumnoGrupoId = 19673
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14861 WHERE ALUG_AlumnoGrupoId = 13829
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 27082 WHERE ALUG_AlumnoGrupoId = 26587
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 18544 WHERE ALUG_AlumnoGrupoId = 17500
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12559 WHERE ALUG_AlumnoGrupoId = 27978
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12560 WHERE ALUG_AlumnoGrupoId = 27979
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 3152 WHERE ALUG_AlumnoGrupoId = 7837
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15237 WHERE ALUG_AlumnoGrupoId = 14205
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 4483 WHERE ALUG_AlumnoGrupoId = 2469
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15840 WHERE ALUG_AlumnoGrupoId = 14807
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 28219 WHERE ALUG_AlumnoGrupoId = 27724
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20584 WHERE ALUG_AlumnoGrupoId = 19535
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 16916 WHERE ALUG_AlumnoGrupoId = 15880
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20374 WHERE ALUG_AlumnoGrupoId = 19325
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 9356 WHERE ALUG_AlumnoGrupoId = 5400
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19090 WHERE ALUG_AlumnoGrupoId = 18043
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29303 WHERE ALUG_AlumnoGrupoId = 28887
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20457 WHERE ALUG_AlumnoGrupoId = 19408
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15895 WHERE ALUG_AlumnoGrupoId = 14862
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 18313 WHERE ALUG_AlumnoGrupoId = 17269
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 18117 WHERE ALUG_AlumnoGrupoId = 17074
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29163 WHERE ALUG_AlumnoGrupoId = 28747
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 28897 WHERE ALUG_AlumnoGrupoId = 28422
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14815 WHERE ALUG_AlumnoGrupoId = 13783
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 16396 WHERE ALUG_AlumnoGrupoId = 15362
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29190 WHERE ALUG_AlumnoGrupoId = 28774
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 4356 WHERE ALUG_AlumnoGrupoId = 8336
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 11893 WHERE ALUG_AlumnoGrupoId = 10881
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29191 WHERE ALUG_AlumnoGrupoId = 28775
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 21058 WHERE ALUG_AlumnoGrupoId = 20002
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15824 WHERE ALUG_AlumnoGrupoId = 14791
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20456 WHERE ALUG_AlumnoGrupoId = 19407
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12351 WHERE ALUG_AlumnoGrupoId = 11335
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 3625 WHERE ALUG_AlumnoGrupoId = 1038
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 11894 WHERE ALUG_AlumnoGrupoId = 10882
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20686 WHERE ALUG_AlumnoGrupoId = 19635
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19482 WHERE ALUG_AlumnoGrupoId = 18434
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14598 WHERE ALUG_AlumnoGrupoId = 13566
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29220 WHERE ALUG_AlumnoGrupoId = 28804
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 13588 WHERE ALUG_AlumnoGrupoId = 12569
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29164 WHERE ALUG_AlumnoGrupoId = 28748
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 28576 WHERE ALUG_AlumnoGrupoId = 28101
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19319 WHERE ALUG_AlumnoGrupoId = 18271
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29177 WHERE ALUG_AlumnoGrupoId = 28761
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 18546 WHERE ALUG_AlumnoGrupoId = 17502
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 8817 WHERE ALUG_AlumnoGrupoId = 5021
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 13361 WHERE ALUG_AlumnoGrupoId = 12342
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 10604 WHERE ALUG_AlumnoGrupoId = 9630
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19321 WHERE ALUG_AlumnoGrupoId = 18273
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 17434 WHERE ALUG_AlumnoGrupoId = 16395
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 18999 WHERE ALUG_AlumnoGrupoId = 17952
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 18187 WHERE ALUG_AlumnoGrupoId = 17144
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15385 WHERE ALUG_AlumnoGrupoId = 14353
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19828 WHERE ALUG_AlumnoGrupoId = 18779
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 2714 WHERE ALUG_AlumnoGrupoId = 5609
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15442 WHERE ALUG_AlumnoGrupoId = 14410
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12494 WHERE ALUG_AlumnoGrupoId = 11477
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 8441 WHERE ALUG_AlumnoGrupoId = 2788
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29165 WHERE ALUG_AlumnoGrupoId = 28749
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19141 WHERE ALUG_AlumnoGrupoId = 18094
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29166 WHERE ALUG_AlumnoGrupoId = 28750
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 21746 WHERE ALUG_AlumnoGrupoId = 21191
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20376 WHERE ALUG_AlumnoGrupoId = 19327
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29192 WHERE ALUG_AlumnoGrupoId = 28776
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 18238 WHERE ALUG_AlumnoGrupoId = 17195
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 11872 WHERE ALUG_AlumnoGrupoId = 10861
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 13074 WHERE ALUG_AlumnoGrupoId = 12055
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20454 WHERE ALUG_AlumnoGrupoId = 19405
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12495 WHERE ALUG_AlumnoGrupoId = 11478
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15499 WHERE ALUG_AlumnoGrupoId = 14467
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12995 WHERE ALUG_AlumnoGrupoId = 11976
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15222 WHERE ALUG_AlumnoGrupoId = 14190
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 13228 WHERE ALUG_AlumnoGrupoId = 12209
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 26491 WHERE ALUG_AlumnoGrupoId = 25996
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 17966 WHERE ALUG_AlumnoGrupoId = 16923
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 11974 WHERE ALUG_AlumnoGrupoId = 10961
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12496 WHERE ALUG_AlumnoGrupoId = 11479
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 17771 WHERE ALUG_AlumnoGrupoId = 16729
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19829 WHERE ALUG_AlumnoGrupoId = 18780
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15500 WHERE ALUG_AlumnoGrupoId = 14468
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15501 WHERE ALUG_AlumnoGrupoId = 14469
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 4146 WHERE ALUG_AlumnoGrupoId = 5195
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 18296 WHERE ALUG_AlumnoGrupoId = 17252
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29178 WHERE ALUG_AlumnoGrupoId = 28762
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 10824 WHERE ALUG_AlumnoGrupoId = 9843
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29216 WHERE ALUG_AlumnoGrupoId = 28800
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 17810 WHERE ALUG_AlumnoGrupoId = 16768
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 5930 WHERE ALUG_AlumnoGrupoId = 8543
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 16413 WHERE ALUG_AlumnoGrupoId = 15379
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 10730 WHERE ALUG_AlumnoGrupoId = 9751
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19094 WHERE ALUG_AlumnoGrupoId = 18047
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29167 WHERE ALUG_AlumnoGrupoId = 28751
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19503 WHERE ALUG_AlumnoGrupoId = 18455
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 28899 WHERE ALUG_AlumnoGrupoId = 28424
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 2672 WHERE ALUG_AlumnoGrupoId = 618
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29198 WHERE ALUG_AlumnoGrupoId = 28782
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 13229 WHERE ALUG_AlumnoGrupoId = 12210
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 10608 WHERE ALUG_AlumnoGrupoId = 9634
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 9415 WHERE ALUG_AlumnoGrupoId = 4355
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 13011 WHERE ALUG_AlumnoGrupoId = 11992
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19487 WHERE ALUG_AlumnoGrupoId = 18439
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 8388 WHERE ALUG_AlumnoGrupoId = 7419
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 10825 WHERE ALUG_AlumnoGrupoId = 9844
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 3598 WHERE ALUG_AlumnoGrupoId = 3280
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14697 WHERE ALUG_AlumnoGrupoId = 13665
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12539 WHERE ALUG_AlumnoGrupoId = 11522
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20463 WHERE ALUG_AlumnoGrupoId = 19414
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14576 WHERE ALUG_AlumnoGrupoId = 13544
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14980 WHERE ALUG_AlumnoGrupoId = 13948
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14599 WHERE ALUG_AlumnoGrupoId = 13567
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20478 WHERE ALUG_AlumnoGrupoId = 19429
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20549 WHERE ALUG_AlumnoGrupoId = 19500
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19680 WHERE ALUG_AlumnoGrupoId = 18632
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19504 WHERE ALUG_AlumnoGrupoId = 18456
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12974 WHERE ALUG_AlumnoGrupoId = 11955
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 3155 WHERE ALUG_AlumnoGrupoId = 5584
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 28531 WHERE ALUG_AlumnoGrupoId = 28056
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29193 WHERE ALUG_AlumnoGrupoId = 28777
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14439 WHERE ALUG_AlumnoGrupoId = 13408
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 17202 WHERE ALUG_AlumnoGrupoId = 20597
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 8205 WHERE ALUG_AlumnoGrupoId = 16163
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15043 WHERE ALUG_AlumnoGrupoId = 14011
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15805 WHERE ALUG_AlumnoGrupoId = 14772
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 16847 WHERE ALUG_AlumnoGrupoId = 15812
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 8464 WHERE ALUG_AlumnoGrupoId = 2514
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 17834 WHERE ALUG_AlumnoGrupoId = 16792
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 13176 WHERE ALUG_AlumnoGrupoId = 12157
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19023 WHERE ALUG_AlumnoGrupoId = 17976
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 21747 WHERE ALUG_AlumnoGrupoId = 21192
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20450 WHERE ALUG_AlumnoGrupoId = 19401
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29150 WHERE ALUG_AlumnoGrupoId = 28734
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20867 WHERE ALUG_AlumnoGrupoId = 19814
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 746 WHERE ALUG_AlumnoGrupoId = 6066
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12998 WHERE ALUG_AlumnoGrupoId = 11979
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 16535 WHERE ALUG_AlumnoGrupoId = 15501
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 27876 WHERE ALUG_AlumnoGrupoId = 27381
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14577 WHERE ALUG_AlumnoGrupoId = 13545
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29237 WHERE ALUG_AlumnoGrupoId = 28821
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29310 WHERE ALUG_AlumnoGrupoId = 28894
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20956 WHERE ALUG_AlumnoGrupoId = 19900
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 2896 WHERE ALUG_AlumnoGrupoId = 1425
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20552 WHERE ALUG_AlumnoGrupoId = 19503
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12354 WHERE ALUG_AlumnoGrupoId = 11338
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 10612 WHERE ALUG_AlumnoGrupoId = 9638
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15502 WHERE ALUG_AlumnoGrupoId = 14470
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 10674 WHERE ALUG_AlumnoGrupoId = 9697
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12143 WHERE ALUG_AlumnoGrupoId = 11127
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12832 WHERE ALUG_AlumnoGrupoId = 11813
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 18700 WHERE ALUG_AlumnoGrupoId = 17654
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 21748 WHERE ALUG_AlumnoGrupoId = 21193
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 3156 WHERE ALUG_AlumnoGrupoId = 3269
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20378 WHERE ALUG_AlumnoGrupoId = 19329
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15436 WHERE ALUG_AlumnoGrupoId = 14404
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 13449 WHERE ALUG_AlumnoGrupoId = 12430
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12977 WHERE ALUG_AlumnoGrupoId = 11958
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 13470 WHERE ALUG_AlumnoGrupoId = 12451
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15504 WHERE ALUG_AlumnoGrupoId = 14472
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 13471 WHERE ALUG_AlumnoGrupoId = 12452
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 22020 WHERE ALUG_AlumnoGrupoId = 21465
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15311 WHERE ALUG_AlumnoGrupoId = 14279
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15899 WHERE ALUG_AlumnoGrupoId = 14866
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12166 WHERE ALUG_AlumnoGrupoId = 11150
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29217 WHERE ALUG_AlumnoGrupoId = 28801
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 23816 WHERE ALUG_AlumnoGrupoId = 23267
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14593 WHERE ALUG_AlumnoGrupoId = 13561
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 18364 WHERE ALUG_AlumnoGrupoId = 17320
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12298 WHERE ALUG_AlumnoGrupoId = 11282
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29168 WHERE ALUG_AlumnoGrupoId = 28752
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 8576 WHERE ALUG_AlumnoGrupoId = 1154
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 13514 WHERE ALUG_AlumnoGrupoId = 12495
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12652 WHERE ALUG_AlumnoGrupoId = 11635
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20732 WHERE ALUG_AlumnoGrupoId = 19680
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19744 WHERE ALUG_AlumnoGrupoId = 18696
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19026 WHERE ALUG_AlumnoGrupoId = 17979
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 9048 WHERE ALUG_AlumnoGrupoId = 799
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 21080 WHERE ALUG_AlumnoGrupoId = 20024
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 16401 WHERE ALUG_AlumnoGrupoId = 15367
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 2718 WHERE ALUG_AlumnoGrupoId = 791
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15505 WHERE ALUG_AlumnoGrupoId = 14473
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15992 WHERE ALUG_AlumnoGrupoId = 14958
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19388 WHERE ALUG_AlumnoGrupoId = 18340
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20379 WHERE ALUG_AlumnoGrupoId = 19330
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 2696 WHERE ALUG_AlumnoGrupoId = 7831
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 5041 WHERE ALUG_AlumnoGrupoId = 7347
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20955 WHERE ALUG_AlumnoGrupoId = 19899
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 16966 WHERE ALUG_AlumnoGrupoId = 15929
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 16420 WHERE ALUG_AlumnoGrupoId = 15386
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 10240 WHERE ALUG_AlumnoGrupoId = 9272
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 6501 WHERE ALUG_AlumnoGrupoId = 6959
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 16419 WHERE ALUG_AlumnoGrupoId = 15385
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 21824 WHERE ALUG_AlumnoGrupoId = 21269
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 11919 WHERE ALUG_AlumnoGrupoId = 10906
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 16294 WHERE ALUG_AlumnoGrupoId = 15260
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 13886 WHERE ALUG_AlumnoGrupoId = 12867
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 11897 WHERE ALUG_AlumnoGrupoId = 10884
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20798 WHERE ALUG_AlumnoGrupoId = 19745
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 18925 WHERE ALUG_AlumnoGrupoId = 17879
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20002 WHERE ALUG_AlumnoGrupoId = 18953
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29195 WHERE ALUG_AlumnoGrupoId = 28779
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29194 WHERE ALUG_AlumnoGrupoId = 28778
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12541 WHERE ALUG_AlumnoGrupoId = 11524
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 10613 WHERE ALUG_AlumnoGrupoId = 9639
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 21033 WHERE ALUG_AlumnoGrupoId = 19977
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 17925 WHERE ALUG_AlumnoGrupoId = 16883
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15570 WHERE ALUG_AlumnoGrupoId = 14538
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14505 WHERE ALUG_AlumnoGrupoId = 13473
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 16207 WHERE ALUG_AlumnoGrupoId = 15173
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 8125 WHERE ALUG_AlumnoGrupoId = 4771
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29218 WHERE ALUG_AlumnoGrupoId = 28802
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 11920 WHERE ALUG_AlumnoGrupoId = 10907
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 21067 WHERE ALUG_AlumnoGrupoId = 20011
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 24524 WHERE ALUG_AlumnoGrupoId = 23975
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 4362 WHERE ALUG_AlumnoGrupoId = 3854
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29169 WHERE ALUG_AlumnoGrupoId = 28753
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19012 WHERE ALUG_AlumnoGrupoId = 17965
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19352 WHERE ALUG_AlumnoGrupoId = 18304
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12481 WHERE ALUG_AlumnoGrupoId = 11465
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19001 WHERE ALUG_AlumnoGrupoId = 17954
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 751 WHERE ALUG_AlumnoGrupoId = 4620
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20775 WHERE ALUG_AlumnoGrupoId = 19722
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 11978 WHERE ALUG_AlumnoGrupoId = 10965
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19328 WHERE ALUG_AlumnoGrupoId = 18280
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19979 WHERE ALUG_AlumnoGrupoId = 18930
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20983 WHERE ALUG_AlumnoGrupoId = 19927
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12088 WHERE ALUG_AlumnoGrupoId = 11072
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29199 WHERE ALUG_AlumnoGrupoId = 28783
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12851 WHERE ALUG_AlumnoGrupoId = 11832
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 8104 WHERE ALUG_AlumnoGrupoId = 5575
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 16209 WHERE ALUG_AlumnoGrupoId = 15175
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12759 WHERE ALUG_AlumnoGrupoId = 11741
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19411 WHERE ALUG_AlumnoGrupoId = 18363
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19145 WHERE ALUG_AlumnoGrupoId = 18098
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19412 WHERE ALUG_AlumnoGrupoId = 18364
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29196 WHERE ALUG_AlumnoGrupoId = 28780
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29170 WHERE ALUG_AlumnoGrupoId = 28754
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12103 WHERE ALUG_AlumnoGrupoId = 11087
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14870 WHERE ALUG_AlumnoGrupoId = 13838
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14580 WHERE ALUG_AlumnoGrupoId = 13548
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 17125 WHERE ALUG_AlumnoGrupoId = 16086
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19511 WHERE ALUG_AlumnoGrupoId = 18463
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 5578 WHERE ALUG_AlumnoGrupoId = 626
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19329 WHERE ALUG_AlumnoGrupoId = 18281
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 2678 WHERE ALUG_AlumnoGrupoId = 3981
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 9177 WHERE ALUG_AlumnoGrupoId = 6304
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12982 WHERE ALUG_AlumnoGrupoId = 11963
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19746 WHERE ALUG_AlumnoGrupoId = 18698
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 28814 WHERE ALUG_AlumnoGrupoId = 28339
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20082 WHERE ALUG_AlumnoGrupoId = 19033
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15421 WHERE ALUG_AlumnoGrupoId = 14389
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20535 WHERE ALUG_AlumnoGrupoId = 19486
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 18551 WHERE ALUG_AlumnoGrupoId = 17507
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 3920 WHERE ALUG_AlumnoGrupoId = 7624
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 482 WHERE ALUG_AlumnoGrupoId = 4280
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19096 WHERE ALUG_AlumnoGrupoId = 18049
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29200 WHERE ALUG_AlumnoGrupoId = 28784
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 28552 WHERE ALUG_AlumnoGrupoId = 28077
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 17205 WHERE ALUG_AlumnoGrupoId = 16166
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 21065 WHERE ALUG_AlumnoGrupoId = 20009
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29171 WHERE ALUG_AlumnoGrupoId = 28755
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19786 WHERE ALUG_AlumnoGrupoId = 18737
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 13276 WHERE ALUG_AlumnoGrupoId = 12257
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 1959 WHERE ALUG_AlumnoGrupoId = 5443
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19957 WHERE ALUG_AlumnoGrupoId = 18908
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 16750 WHERE ALUG_AlumnoGrupoId = 15716
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 2652 WHERE ALUG_AlumnoGrupoId = 4491
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 28530 WHERE ALUG_AlumnoGrupoId = 28055
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 4412 WHERE ALUG_AlumnoGrupoId = 1691
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12340 WHERE ALUG_AlumnoGrupoId = 11324
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29201 WHERE ALUG_AlumnoGrupoId = 28785
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 16404 WHERE ALUG_AlumnoGrupoId = 15370
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 21127 WHERE ALUG_AlumnoGrupoId = 29032
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19330 WHERE ALUG_AlumnoGrupoId = 18282
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 16011 WHERE ALUG_AlumnoGrupoId = 14977
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 25793 WHERE ALUG_AlumnoGrupoId = 25298
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12655 WHERE ALUG_AlumnoGrupoId = 11638
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19353 WHERE ALUG_AlumnoGrupoId = 18305
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20971 WHERE ALUG_AlumnoGrupoId = 19915
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 10386 WHERE ALUG_AlumnoGrupoId = 9415
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 5241 WHERE ALUG_AlumnoGrupoId = 4254
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12321 WHERE ALUG_AlumnoGrupoId = 11305
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12835 WHERE ALUG_AlumnoGrupoId = 11816
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 21749 WHERE ALUG_AlumnoGrupoId = 21194
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 16163 WHERE ALUG_AlumnoGrupoId = 15129
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 11879 WHERE ALUG_AlumnoGrupoId = 10868
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19099 WHERE ALUG_AlumnoGrupoId = 18052
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20032 WHERE ALUG_AlumnoGrupoId = 18983
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 21750 WHERE ALUG_AlumnoGrupoId = 21195
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20452 WHERE ALUG_AlumnoGrupoId = 19403
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 10436 WHERE ALUG_AlumnoGrupoId = 9464
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 16997 WHERE ALUG_AlumnoGrupoId = 15960
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 436 WHERE ALUG_AlumnoGrupoId = 8345
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12781 WHERE ALUG_AlumnoGrupoId = 11762
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15507 WHERE ALUG_AlumnoGrupoId = 14475
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19354 WHERE ALUG_AlumnoGrupoId = 18306
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20968 WHERE ALUG_AlumnoGrupoId = 19912
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 18529 WHERE ALUG_AlumnoGrupoId = 17485
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 13078 WHERE ALUG_AlumnoGrupoId = 12059
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14442 WHERE ALUG_AlumnoGrupoId = 13411
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 9302 WHERE ALUG_AlumnoGrupoId = 7140
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19934 WHERE ALUG_AlumnoGrupoId = 18885
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12656 WHERE ALUG_AlumnoGrupoId = 11639
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20114 WHERE ALUG_AlumnoGrupoId = 19065
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 18685 WHERE ALUG_AlumnoGrupoId = 17640
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20447 WHERE ALUG_AlumnoGrupoId = 19398
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14604 WHERE ALUG_AlumnoGrupoId = 13572
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15028 WHERE ALUG_AlumnoGrupoId = 13996
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 6841 WHERE ALUG_AlumnoGrupoId = 1486
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 11958 WHERE ALUG_AlumnoGrupoId = 10945
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19331 WHERE ALUG_AlumnoGrupoId = 18283
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14581 WHERE ALUG_AlumnoGrupoId = 13549
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 13855 WHERE ALUG_AlumnoGrupoId = 12836
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 16039 WHERE ALUG_AlumnoGrupoId = 15005
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 21753 WHERE ALUG_AlumnoGrupoId = 21198
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14988 WHERE ALUG_AlumnoGrupoId = 13956
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 16057 WHERE ALUG_AlumnoGrupoId = 15023
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19983 WHERE ALUG_AlumnoGrupoId = 18934
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 8209 WHERE ALUG_AlumnoGrupoId = 8817
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 5940 WHERE ALUG_AlumnoGrupoId = 5883
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14601 WHERE ALUG_AlumnoGrupoId = 13569
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 5014 WHERE ALUG_AlumnoGrupoId = 8105
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 17105 WHERE ALUG_AlumnoGrupoId = 16067
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29172 WHERE ALUG_AlumnoGrupoId = 28756
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 21730 WHERE ALUG_AlumnoGrupoId = 21175
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20449 WHERE ALUG_AlumnoGrupoId = 19400
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15508 WHERE ALUG_AlumnoGrupoId = 14476
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 18749 WHERE ALUG_AlumnoGrupoId = 17703
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19100 WHERE ALUG_AlumnoGrupoId = 18053
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14569 WHERE ALUG_AlumnoGrupoId = 13537
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 15869 WHERE ALUG_AlumnoGrupoId = 14836
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 21093 WHERE ALUG_AlumnoGrupoId = 20037
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 28195 WHERE ALUG_AlumnoGrupoId = 27700
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 10785 WHERE ALUG_AlumnoGrupoId = 9805
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19175 WHERE ALUG_AlumnoGrupoId = 18128
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20950 WHERE ALUG_AlumnoGrupoId = 19894
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 21731 WHERE ALUG_AlumnoGrupoId = 21176
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12070 WHERE ALUG_AlumnoGrupoId = 11054
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29173 WHERE ALUG_AlumnoGrupoId = 28757
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29197 WHERE ALUG_AlumnoGrupoId = 28781
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29219 WHERE ALUG_AlumnoGrupoId = 28803
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 14696 WHERE ALUG_AlumnoGrupoId = 13664
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 23452 WHERE ALUG_AlumnoGrupoId = 22903
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20318 WHERE ALUG_AlumnoGrupoId = 19269
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20597 WHERE ALUG_AlumnoGrupoId = 19548
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 21732 WHERE ALUG_AlumnoGrupoId = 21177
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12362 WHERE ALUG_AlumnoGrupoId = 11346
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12657 WHERE ALUG_AlumnoGrupoId = 11640
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 12658 WHERE ALUG_AlumnoGrupoId = 11641
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 18444 WHERE ALUG_AlumnoGrupoId = 17400
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 16424 WHERE ALUG_AlumnoGrupoId = 15390
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 19355 WHERE ALUG_AlumnoGrupoId = 18307
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29247 WHERE ALUG_AlumnoGrupoId = 28831
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 20243 WHERE ALUG_AlumnoGrupoId = 19194
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 2351 WHERE ALUG_AlumnoGrupoId = 8124
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29174 WHERE ALUG_AlumnoGrupoId = 28758
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 21733 WHERE ALUG_AlumnoGrupoId = 21178
UPDATE [dbo].[AlumnosGrupos] SET ALUG_INS_InscripcionId = 29202 WHERE ALUG_AlumnoGrupoId = 28786

DELETE FROM AlumnosGrupos WHERE ALUG_AlumnoGrupoId = 6794
DELETE FROM AlumnosGrupos WHERE ALUG_AlumnoGrupoId = 29343
DELETE FROM AlumnosGrupos WHERE ALUG_AlumnoGrupoId = 18329
DELETE FROM AlumnosGrupos WHERE ALUG_AlumnoGrupoId = 27853
DELETE FROM AlumnosGrupos WHERE ALUG_AlumnoGrupoId = 4086
DELETE FROM AlumnosGrupos WHERE ALUG_AlumnoGrupoId = 438

update AlumnosGrupos
	set ALUG_PROGRU_GrupoId = INS_PROGRU_GrupoId
from 
	AlumnosGrupos 
	inner join Inscripciones on ALUG_INS_InscripcionId = INS_InscripcionId 
where 
	ALUG_PROGRU_GrupoId <> INS_PROGRU_GrupoId
	and (select COUNT(*) from AlumnosGrupos where ALUG_ALU_AlumnoId = INS_ALU_AlumnoId and ALUG_PROGRU_GrupoId = INS_PROGRU_GrupoId) = 0
go