EXEC sp_rename 'dbo.ClientesFacturacion.CLIF_NumeroINTerior', 'CLIF_NumeroInterior', 'COLUMN';

ALTER TABLE AlumnosFacturacion ALTER COLUMN ALUF_Calle VARCHAR(250) NULL
GO
ALTER TABLE AlumnosFacturacion ALTER COLUMN ALUF_NumeroExterior VARCHAR(10) NULL
GO
ALTER TABLE AlumnosFacturacion ALTER COLUMN ALUF_Colonia VARCHAR(250) NULL
GO
ALTER TABLE AlumnosFacturacion ALTER COLUMN ALUF_PAI_PaisId SMALLINT NULL
GO
ALTER TABLE AlumnosFacturacion ALTER COLUMN ALUF_EST_EstadoId INT NULL
GO
ALTER TABLE AlumnosFacturacion ALTER COLUMN ALUF_CorreoElectronico VARCHAR(50) NULL
GO

ALTER TABLE ClientesFacturacion ALTER COLUMN CLIF_Calle VARCHAR(250) NULL
GO
ALTER TABLE ClientesFacturacion ALTER COLUMN CLIF_NumeroExterior VARCHAR(10) NULL
GO
ALTER TABLE ClientesFacturacion ALTER COLUMN CLIF_Colonia VARCHAR(250) NULL
GO
ALTER TABLE ClientesFacturacion ALTER COLUMN CLIF_PAI_PaisId SMALLINT NULL
GO
ALTER TABLE ClientesFacturacion ALTER COLUMN CLIF_EST_EstadoId INT NULL
GO
ALTER TABLE ClientesFacturacion ALTER COLUMN CLIF_Ciudad VARCHAR(100) NULL
GO
ALTER TABLE ClientesFacturacion ALTER COLUMN CLIF_CorreoElectronico VARCHAR(50) NULL
GO