DROP INDEX IX_PROGRUCOD_Unique ON ProgramasGrupos
GO

CREATE UNIQUE INDEX IX_PROGRUCOD_Unique
ON ProgramasGrupos(PROGRU_Codigo,PROGRU_FechaInicio,PROGRU_CMM_EstatusId)
WHERE PROGRU_CMM_EstatusId = 2000620 AND PROGRU_PGINCG_ProgramaIncompanyId IS NULL
GO

ALTER TABLE ProgramasGrupos
DROP COLUMN PROGRU_Activo
GO