ALTER TABLE CXCFacturas ALTER COLUMN CXCF_FP_FormaPagoId	SMALLINT NULL
GO

ALTER TABLE CXCFacturas ALTER COLUMN CXCF_DiasCredito	INT NULL
GO

ALTER TABLE CXCFacturas ALTER COLUMN CXCF_MON_MonedaId	SMALLINT NULL
GO

ALTER TABLE CXCFacturas ALTER COLUMN CXCF_TipoCambio	DECIMAL (28, 4) NULL
GO

ALTER TABLE CXCFacturas ALTER COLUMN CXCF_CMM_MetodoPagoId	INT NULL
GO

ALTER TABLE CXCFacturasDetalles ALTER COLUMN CXCFD_NoIdentificacion	VARCHAR(100) NULL
GO

ALTER TABLE CXCFacturasDetalles ALTER COLUMN CXCFD_Descuento	DECIMAL (28, 6) NULL
GO