DROP TABLE IF EXISTS CXCPagosDetalles
GO
DROP TABLE IF EXISTS CXCPagos
GO

-- Creamos la tabla para la cabecera
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE CXCPagos (
	CXCP_PagoId INT IDENTITY(1,1) NOT NULL,
	CXCP_CXCF_FacturaId INT NOT NULL,
	
	CXCP_Version VARCHAR(10) NOT NULL,
	CXCP_Fecha DATETIME NOT NULL,
	CXCP_FP_FormaPagoId SMALLINT NOT NULL,
	CXCP_MON_MonedaId SMALLINT NOT NULL,
	CXCP_TipoCambio DECIMAL(28, 4) NOT NULL,
	CXCP_NoOperacion VARCHAR(100) NULL,

	CXCP_CuentaOrdenante VARCHAR(4000) NULL,
	CXCP_CuentaOrdenanteEmisorRFC VARCHAR(4000) NULL,
	CXCP_CuentaOrdenanteNombreBanco VARCHAR(4000) NULL,

	CXCP_CuentaBeneficiario VARCHAR(4000) NULL,
	CXCP_CuentaBeneficiarioEmisorRFC VARCHAR(4000) NULL
 CONSTRAINT PK_CXCPagos PRIMARY KEY CLUSTERED 
(
	CXCP_PagoId ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE CXCPagos  WITH CHECK ADD  CONSTRAINT FK_CXCPagos_Factura FOREIGN KEY(CXCP_CXCF_FacturaId)
REFERENCES CXCFacturas (CXCF_FacturaId)
GO
ALTER TABLE CXCPagos CHECK CONSTRAINT FK_CXCPagos_Factura
GO

ALTER TABLE CXCPagos  WITH CHECK ADD  CONSTRAINT FK_CXCPagos_FormasPago FOREIGN KEY(CXCP_FP_FormaPagoId)
REFERENCES FormasPago (FP_FormaPagoId)
GO
ALTER TABLE CXCPagos CHECK CONSTRAINT FK_CXCPagos_FormasPago
GO

ALTER TABLE CXCPagos  WITH CHECK ADD  CONSTRAINT FK_CXCPagos_Monedas FOREIGN KEY(CXCP_MON_MonedaId)
REFERENCES Monedas (MON_MonedaId)
GO
ALTER TABLE CXCPagos CHECK CONSTRAINT FK_CXCPagos_Monedas
GO

-- Creamos la tabla para los detalles
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE CXCPagosDetalles (
	CXCPD_PagoDetalleId INT IDENTITY(1,1) NOT NULL,
	CXCPD_CXCP_PagoId INT NOT NULL,
	CXCPD_CXCF_DoctoRelacionadoId INT NOT NULL,
	CXCPD_NoParcialidad INT NOT NULL,
	CXCPD_ImporteSaldoAnterior DECIMAL (28, 6) NOT NULL,
	CXCPD_ImportePagado DECIMAL (28, 6) NOT NULL,
	CXCPD_ImporteSaldoInsoluto DECIMAL (28, 6) NOT NULL,
	CXCPD_CMM_ObjetoImpuestoId INT NULL
 CONSTRAINT PK_CXCPagosDetalles PRIMARY KEY CLUSTERED 
(
	CXCPD_PagoDetalleId ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE CXCPagosDetalles  WITH CHECK ADD  CONSTRAINT FK_CXCPagosDetalles_PagoId FOREIGN KEY(CXCPD_CXCP_PagoId)
REFERENCES CXCPagos (CXCP_PagoId)
GO
ALTER TABLE CXCPagosDetalles CHECK CONSTRAINT FK_CXCPagosDetalles_PagoId
GO

ALTER TABLE CXCPagosDetalles  WITH CHECK ADD  CONSTRAINT FK_CXCPagosDetalles_DoctoRelacionadoId FOREIGN KEY(CXCPD_CXCF_DoctoRelacionadoId)
REFERENCES CXCFacturas (CXCF_FacturaId)
GO
ALTER TABLE CXCPagosDetalles CHECK CONSTRAINT FK_CXCPagosDetalles_DoctoRelacionadoId
GO

ALTER TABLE CXCPagosDetalles  WITH CHECK ADD  CONSTRAINT FK_CXCPagosDetalles_ObjetosImpuesto FOREIGN KEY(CXCPD_CMM_ObjetoImpuestoId)
REFERENCES ControlesMaestrosMultiples (CMM_ControlId)
GO
ALTER TABLE CXCPagosDetalles CHECK CONSTRAINT FK_CXCPagosDetalles_ObjetosImpuesto
GO