package com.pixvs.main.models.cfdi;

import java.util.HashMap;
import java.util.Map;

public class MatrizErrores {

    private static Map<String, String> errores = new HashMap<String, String>() {{
        // Errores Generales
        put("301", "El CFDI no tiene una estructura XML correcta.");
        put("302", "El sello del emisor no es válido.");
        put("303", "El Certificado de Sello Digital no corresponde al contribuyente emisor.");
        put("304", "El certificado se encuentra revocado o caducó.");
        put("305", "La fecha del CFDI está fuera del rango de la validez del certificado.");
        put("306", "El certificado usado para generar el sello digital no es un Certificado de Sello Digital.");
        put("308", "El certificado utilizado para generar el sello digital no ha sido emitido por el SAT.");
        put("401", "La fecha del comprobante está fuera del rango de timbrado permitido.");
        put("402", "El contribuyente no se encuentra dentro del régimen fiscal para emitir CFDI.");
        put("611", "Los parámetros recibidos están incompletos o no se encuentran donde se esperarían.");

        put("CFDI33338", "Usuario o contraseña incorrecto.");
        put("CFDI33382", "No existe el nodo Impuestos a nivel Comprobante.");

        put("CFDI301", "El CFDI no tiene una estructura XML correcta.");
        put("CFDI302", "El sello del emisor no es válido.");
        put("CFDI303", "El Certificado de Sello Digital no corresponde al contribuyente emisor.");
        put("CFDI304", "El certificado se encuentra revocado o caducó.");
        put("CFDI305", "La fecha del CFDI está fuera del rango de la validez del certificado.");
        put("CFDI306", "El certificado usado para generar el sello digital no es un Certificado de Sello Digital.");
        put("CFDI308", "El certificado utilizado para generar el sello digital no ha sido emitido por el SAT.");
        put("CFDI401", "La fecha del comprobante está fuera del rango de timbrado permitido.");
        put("CFDI402", "El contribuyente no se encuentra dentro del régimen fiscal para emitir CFDI.");
        put("CFDI611", "Los parámetros recibidos están incompletos o no se encuentran donde se esperarían.");

        // Versión 3.3
        put("CFDI33101", "El campo Fecha no cumple con el patrón requerido.");
        put("CFDI33102", "El resultado de la digestión debe ser igual al resultado de la desencripción del sello.");
        put("CFDI33103", "Si existe el complemento para recepción de pagos el campo FormaPago no debe existir.");
        put("CFDI33104", "El campo FormaPago no contiene un valor del catálogo c_FormaPago. ");
        put("CFDI33105", "EL certificado no cumple con alguno de los valores permitidos.");
        put("CFDI33106", "El valor de este campo SubTotal excede la cantidad de decimales que soporta la moneda.");
        put("CFDI33107", "El TipoDeComprobante es I,E o N, el importe registrado en el campo no es igual a la suma de los importes de los conceptos registrados.");
        put("CFDI33108", "El TipoDeComprobante es T o P y el importe no es igual a 0, o cero con decimales.");
        put("CFDI33109", "El valor registrado en el campo Descuento no es menor o igual que el campo Subtotal.");
        put("CFDI33110", "El TipoDeComprobante no es I,E o N, y un concepto incluye el campo descuento. ");
        put("CFDI33111", "El valor del campo Descuento excede la cantidad de decimales que soporta la moneda.");
        put("CFDI33112", "El campo Moneda no contiene un valor del catálogo c_Moneda. ");
        put("CFDI33113", "El campo TipoCambio no tiene el valor '1' y la moneda indicada es MXN.");
        put("CFDI33114", "El campo TipoCambio se debe registrar cuando el campo Moneda tiene un valor distinto de MXN y XXX. ");
        put("CFDI33115", "El campo TipoCambio no se debe registrar cuando el campo Moneda tiene el valor XXX.");
        put("CFDI33116", "El campo TipoCambio no cumple con el patrón requerido.");
        put("CFDI33117", "Cuando el valor del campo TipoCambio se encuentre fuera de los límites establecidos, debe existir el campo Confirmacion.");
        put("CFDI33118", "El campo Total no corresponde con la suma del subtotal, menos los descuentos aplicables, más las contribuciones recibidas (impuestos trasladados - federales o locales, derechos, productos, aprovechamientos, aportaciones de seguridad social, contribuciones de mejoras) menos los impuestos retenidos.");
        put("CFDI33119", "Cuando el valor del campo Total se encuentre fuera de los límites establecidos, debe existir el campo Confirmacion.");
        put("CFDI33120", "El campo TipoDeComprobante, no contiene un valor del catálogo c_TipoDeComprobante.");
        put("CFDI33121", "El campo MetodoPago, no contiene un valor del catálogo c_MetodoPago.");
        put("CFDI33122", "Cuando se tiene el valor PIP en el campo MetodoPago y el valor en el campo TipoDeComprobante es I ó E, el CFDI debe contener un complemento de recibo de pago.");
        put("CFDI33123", "Se debe omitir el campo MetodoPago cuando el TipoDeComprobante es T o P.");
        put("CFDI33124", "Si existe el complemento para recepción de pagos en este CFDI el campo MetodoPago no debe existir.");
        put("CFDI33125", "El campo LugarExpedicion, no contiene un valor del catálogo c_CodigoPostal.");
        put("CFDI33126", "El campo Confirmacion no debe existir cuando los atributos TipoCambio y/o Total están dentro del rango permitido.");
        put("CFDI33127", "Número de confirmación inválido.");
        put("CFDI33128", "Número de confirmación utilizado previamente.");
        put("CFDI33129", "El campo TipoRelacion, no contiene un valor del catálogo c_TipoRelacion.");
        put("CFDI33130", "El campo RegimenFiscal, no contiene un valor del catálogo c_RegimenFiscal.");
        put("CFDI33131", "La clave del campo RegimenFiscal debe corresponder con el tipo de persona (fisica o moral).");
        put("CFDI33132", "Este RFC del receptor no existe en la lista de RFC inscritos no cancelados del SAT.");
        put("CFDI33133", "El campo ResidenciaFiscal, no contiene un valor del catálogo c_Pais.");
        put("CFDI33134", "El RFC del receptor es de un RFC registrado en el SAT o un RFC genérico nacional y existe el campo ResidenciaFiscal.");
        put("CFDI33135", "El valor del campo ResidenciaFiscal no puede ser MEX.");
        put("CFDI33136", "Se debe registrar un valor de acuerdo al catálogo c_Pais en en el campo ResidenciaFiscal, cuando en el en el campo NumRegIdTrib se registre información.");
        put("CFDI33137", "El valor del campo es un RFC inscrito no cancelado en el SAT o un RFC genérico nacional, y se registró el campo NumRegIdTrib.");
        put("CFDI33138", "Para registrar el campo NumRegIdTrib, el CFDI debe contener el complemento de comercio exterior y el RFC del receptor debe ser un RFC genérico extranjero.");
        put("CFDI33139", "El campo NumRegIdTrib no cumple con el patrón correspondiente. ");
        put("CFDI33140", "El campo UsoCFDI, no contiene un valor del catálogo c_UsoCFDI.");
        put("CFDI33141", "La clave del campo UsoCFDI debe corresponder con el tipo de persona (fisica o moral).");
        put("CFDI33142", "El campo ClaveProdServ, no contiene un valor del catálogo c_ClaveProdServ.");
        put("CFDI33143", "No existe el complemento requerido para el valor de ClaveProdServ.");
        put("CFDI33144", "No está declarado el impuesto relacionado con el valor de ClaveProdServ.");
        put("CFDI33145", "El campo ClaveUnidad no contiene un valor del catálogo c_ClaveUnidad.");
        put("CFDI33146", "El valor del campo ValorUnitario debe tener hasta la cantidad de decimales que soporte la moneda.");
        put("CFDI33147", "El valor valor del campo ValorUnitario debe ser mayor que cero (0) cuando el tipo de comprobante es Ingreso, Egreso o Nomina.");
        put("CFDI33148", "El valor del campo Importe debe tener hasta la cantidad de decimales que soporte la moneda.");
        put("CFDI33149", "El valor del campo Importe no se encuentra entre el limite inferior y superior permitido.");
        put("CFDI33150", "El valor del campo Descuento debe tener hasta la cantidad de decimales que tenga registrado el atributo importe del concepto.");
        put("CFDI33151", "El valor del campo Descuento es mayor que el campo Importe.");
        put("CFDI33152", "En caso de utilizar el nodo Impuestos en un concepto, se deben incluir impuestos  de traslado y/o retenciones.");
        put("CFDI33153", "El valor del campo Base que corresponde a Traslado debe tener hasta la cantidad de decimales que soporte la moneda.");
        put("CFDI33154", "El valor del campo Base que corresponde a Traslado debe ser mayor que cero.");
        put("CFDI33155", "El valor del campo Impuesto que corresponde a Traslado no contiene un valor del catálogo c_Impuesto.");
        put("CFDI33156", "El valor del campo TipoFactor que corresponde a Traslado no contiene un valor del catálogo c_TipoFactor.");
        put("CFDI33157", "Si el valor registrado en el campo TipoFactor que corresponde a Traslado es Exento no se deben registrar los campos TasaOCuota ni Importe.");
        put("CFDI33158", "Si el valor registrado en el campo TipoFactor que corresponde a Traslado es Tasa o Cuota, se deben registrar los campos TasaOCuota e Importe.");
        put("CFDI33159", "El valor del campo TasaOCuota que corresponde a Traslado no contiene un valor del catálogo c_TasaOcuota o se encuentra fuera de rango.");
        put("CFDI33160", "El valor del campo Importe que corresponde a Traslado debe tener hasta la cantidad de decimales que soporte la moneda.");
        put("CFDI33161", "El valor del campo Importe o que corresponde a Traslado no se encuentra entre el limite inferior y superior permitido.");
        put("CFDI33162", "El valor del campo Base que corresponde a Retención debe tener hasta la cantidad de decimales que soporte la moneda.");
        put("CFDI33163", "El valor del campo Base que corresponde a Retención debe ser mayor que cero.");
        put("CFDI33164", "El valor del campo Impuesto que corresponde a Retención no contiene un valor del catálogo c_Impuesto.");
        put("CFDI33165", "El valor del campo TipoFactor que corresponde a Retención no contiene un valor del catálogo c_TipoFactor.");
        put("CFDI33166", "Si el valor registrado en el campo TipoFactor que corresponde a Retención debe ser distinto de Exento.");
        put("CFDI33167", "El valor del campo TasaOCuota que corresponde a Retención, no contiene un valor del catálogo c_TasaOcuota o se encuentra fuera de rango.");
        put("CFDI33168", "El valor del campo Importe que corresponde a Retención debe tener hasta la cantidad de decimales que soporte la moneda.");
        put("CFDI33169", "El valor del campo Importe que corresponde a Retención no se encuentra entre el limite inferior y superior permitido.");
        put("CFDI33170", "El número de pedimento es inválido.");
        put("CFDI33171", "El NumeroPedimento no debe existir si se incluye el complemento de comercio exterior.");
        put("CFDI33172", "El campo ClaveProdServ, no contiene un valor del catálogo c_ClaveProdServ.");
        put("CFDI33173", "El valor del campo ValorUnitario debe tener hasta la cantidad de decimales que soporte la moneda.");
        put("CFDI33174", "El valor del campo ValorUnitario debe ser mayor que cero (0).");
        put("CFDI33175", "El valor del campo Importe debe tener hasta la cantidad de decimales que soporte la moneda.");
        put("CFDI33176", "El valor del campo Importe no se encuentra entre el limite inferior y superior permitido.");
        put("CFDI33177", "El número de pedimento es inválido.");
        put("CFDI33178", "El NumeroPedimento no debe existir si se incluye el complemento de comercio exterior.");
        put("CFDI33179", "Cuando el TipoDeComprobante sea T o P, el elemento Impuestos no debe existir.");
        put("CFDI33180", "El valor del campo TotalImpuestosRetenidos debe tener hasta la cantidad de decimales que soporte la moneda.");
        put("CFDI33181", "El valor del campo TotalImpuestosRetenidos debe ser igual a la suma de los importes registrados en el elemento hijo Retencion.");
        put("CFDI33182", "El valor del campo TotalImpuestosTrasladados debe tener hasta la cantidad de decimales que soporte la moneda.");
        put("CFDI33183", "El valor del campo TotalImpuestosTrasladados no es igual a la suma de los importes registrados en el elemento hijo Traslado.");
        put("CFDI33184", "Debe existir el campo TotalImpuestosRetenidos.");
        put("CFDI33185", "El campo Impuesto no contiene un valor del catálogo c_Impuesto.");
        put("CFDI33186", "Debe haber sólo un registro por cada tipo de impuesto retenido.");
        put("CFDI33187", "Debe existir el campo TotalImpuestosRetenidos.");
        put("CFDI33188", "El valor del campo Importe correspondiente a Retención debe tener hasta la cantidad de decimales que soporte la moneda.");
        put("CFDI33189", "El campo Importe correspondiente a Retención no es igual a la suma de los importes de los impuestos retenidos registrados en los conceptos donde el impuesto sea igual al campo impuesto de este elemento.");
        put("CFDI33190", "Debe existir el campo TotalImpuestosTrasladados.");
        put("CFDI33191", "El campo Impuesto no contiene un valor del catálogo c_Impuesto.");
        put("CFDI33192", "Debe haber sólo un registro con la misma combinación de impuesto, factor y tasa por cada traslado.");
        put("CFDI33193", "El valor seleccionado debe corresponder a un valor del catalogo donde la columna impuesto corresponda con el campo impuesto y la columna factor corresponda con el campo TipoFactor.");
        put("CFDI33194", "El valor del campo Importe correspondiente a Traslado debe tener hasta la cantidad de decimales que soporte la moneda.");
        put("CFDI33195", "El campo Importe correspondiente a Traslado no es igual a la suma de los importes de los impuestos trasladados registrados en los conceptos donde el impuesto del concepto sea igual al campo impuesto de este elemento y la TasaOCuota del concepto sea igual al campo TasaOCuota de este elemento.");
        put("CFDI33196", "Error no identificado.");

        put("CRP101", "El valor del campo TipoDeComprobante debe ser 'P'");
        put("CRP102", "El valor del campo SubTotal debe ser cero '0'.");
        put("CRP103", "El valor del campo Moneda debe ser 'XXX'.");
        put("CRP104", "El campo FormaPago no se debe registrar en el CFDI.");
        put("CRP105", "El campo MetodoPago no se debe registrar en el CFDI.");
        put("CRP106", "El campo CondicionesDePago no se debe registrar en el CFDI.");
        put("CRP107", "El campo Descuento no se debe registrar en el CFDI.");
        put("CRP108", "El campo TipoCambio no se debe registrar en el CFDI.");
        put("CRP109", "El valor del campo Total debe ser cero '0'.");
        put("CRP110", "El valor del campo UsoCFDI debe ser 'P01'.");
        put("CRP111", "Solo debe existir un Concepto en el CFDI. ");
        put("CRP112", "No se deben registrar apartados dentro de Conceptos");
        put("CRP113", "El valor del campo ClaveProdServ debe ser '84111506'.");
        put("CRP114", "El campo NoIdentificacion no se debe registrar en el CFDI.");
        put("CRP115", "El valor del campo Cantidad debe ser '1'.");
        put("CRP116", "El valor del campo ClaveUnidad debe ser 'ACT'.");
        put("CRP117", "El campo Unidad no se debe registrar en el CFDI.");
        put("CRP118", "El valor del campo Descripcion debe ser 'Pago'.");
        put("CRP119", "El valor del campo ValorUnitario debe ser cero '0'.");
        put("CRP120", "El valor del campo Importe debe ser cero '0'.");
        put("CRP121", "El campo Descuento no se debe registrar en el CFDI.");
        put("CRP122", "No se debe registrar el apartado de Impuestos en el CFDI.");
        put("CRP201", "El valor del campo FormaDePagoP debe ser distinto de '99'.");
        put("CRP202", "El campo MonedaP debe ser distinto de 'XXX'");
        put("CRP203", "El campo TipoCambioP se debe registrar. ");
        put("CRP204", "El campo TipoCambioP no se debe registrar. ");
        put("CRP205", "Cuando el valor del campo TipoCambioP se encuentre fuera de los límites establecidos, debe existir el campo Confirmacion");
        put("CRP206", "La suma de los valores registrados en el campo ImpPagado de los apartados DoctoRelacionado no es menor o igual que el valor del campo Monto.");
        put("CRP207", "El valor del campo Monto no es mayor que cero '0'.");
        put("CRP208", "El valor del campo Monto debe tener hasta la cantidad de decimales que soporte la moneda registrada en el campo MonedaP.");
        put("CRP209", "Cuando el valor del campo Monto se encuentre fuera de los límites establecidos, debe existir el campo Confirmacion");
        put("CRP210", "El RFC del campo RfcEmisorCtaOrd no se encuentra en la lista de RFC.");
        put("CRP211", "El campo NomBancoOrdExt se debe registrar. ");
        put("CRP212", "El campo CtaOrdenante no se debe registrar. ");
        put("CRP213", "El campo CtaOrdenante no cumple con el patrón requerido.");
        put("CRP214", "El campo RfcEmisorCtaBen no se debe registrar. ");
        put("CRP215", "El campo CtaBeneficiario no se debe registrar. ");
        put("CRP216", "El campo TipoCadPago no se debe registrar. ");
        put("CRP217", "El valor del campo MonedaDR debe ser distinto de 'XXX'");
        put("CRP218", "El campo TipoCambioDR se debe registrar. ");
        put("CRP219", "El campo TipoCambioDR no se debe registrar. ");
        put("CRP220", "El campo TipoCambioDR debe ser '1'. ");
        put("CRP221", "El campo ImpSaldoAnt debe mayor a cero.");
        put("CRP222", "El valor del campo ImpSaldoAnt debe tener hasta la cantidad de decimales que soporte la moneda registrada en el campo MonedaDR.");
        put("CRP223", "El campo ImpPagado debe mayor a cero.");
        put("CRP224", "El valor del campo ImpPagado debe tener hasta la cantidad de decimales que soporte la moneda registrada en el campo MonedaDR.");
        put("CRP225", "El valor del campo ImpSaldoInsoluto debe tener hasta la cantidad de decimales que soporte la moneda registrada en el campo MonedaDR.");
        put("CRP226", "El campo ImpSaldoInsoluto debe ser mayor o igual a cero y calcularse con la suma de los campos ImSaldoAnt menos el ImpPagado o el Monto.");
        put("CRP227", "El campo CertPago se debe registrar. ");
        put("CRP228", "El campo CertPago no se debe registrar. ");
        put("CRP229", "El campo CadPago se debe registrar. ");
        put("CRP230", "El campo CadPago no se debe registrar. ");
        put("CRP231", "El campo SelloPago se debe registrar. ");
        put("CRP232", "El campo SelloPago no se debe registrar. ");
        put("CRP233", "El campo NumParcialidad se debe registrar. ");
        put("CRP234", "El campo ImpSaldoAnt se debe registrar. ");
        put("CRP235", "El campo ImpPagado se debe registrar. ");
        put("CRP236", "El campo ImpSaldoInsoluto se debe registrar. ");
        put("CRP237", "No debe existir el apartado de Impuestos.");
        put("CRP238", "El campo RfcEmisorCtaOrd no se debe registrar.");
        put("CRP239", "El campo CtaBeneficiario no cumple con el patrón requerido.");
        put("CRP999", "Error no clasificado");

        // Versión 4.0
        put("CFDI40101", "El campo Fecha no cumple con el patrón requerido.");
        put("CFDI40102", "El resultado de la digestión debe ser igual al resultado de la desencripción del sello.");
        put("CFDI40103", "Si existe el tipo de comprobante T, N o P el campo FormaPago no debe existir.");
        put("CFDI40104", "El campo FormaPago no contiene un valor del catálogo c_FormaPago. ");
        put("CFDI40105", "El campo FormaPago no contiene el valor '99'. ");
        put("CFDI40106", "EL certificado no cumple con alguno de los valores permitidos.");
        put("CFDI40107", "El valor de este campo SubTotal excede la cantidad de decimales que soporta la moneda.");
        put("CFDI40108", "El TipoDeComprobante es I,E o N, el importe registrado en el campo no es igual al redondeo de la suma de los importes de los conceptos registrados.");
        put("CFDI40109", "El TipoDeComprobante es T o P y el importe no es igual a 0, o cero con decimales.");
        put("CFDI40110", "El valor registrado en el campo Descuento no es menor o igual que el campo Subtotal.");
        put("CFDI40111", "El TipoDeComprobante no es I,E o N, y un concepto incluye el campo descuento. ");
        put("CFDI40112", "El valor del campo Descuento excede la cantidad de decimales que soporta la moneda.");
        put("CFDI40113", "El campo Moneda no contiene un valor del catálogo c_Moneda. ");
        put("CFDI40114", "El campo TipoCambio no tiene el valor '1' y la moneda indicada es MXN.");
        put("CFDI40115", "El campo TipoCambio se debe registrar cuando el campo Moneda tiene un valor distinto de MXN y XXX. ");
        put("CFDI40116", "El campo TipoCambio no se debe registrar cuando el campo Moneda tiene el valor XXX.");
        put("CFDI40117", "El campo TipoCambio no cumple con el patrón requerido.");
        put("CFDI40118", "Cuando el valor del campo TipoCambio se encuentre fuera de los límites establecidos, debe existir el campo Confirmacion.");
        put("CFDI40119", "El campo Total no corresponde con la suma del subtotal, menos los descuentos aplicables, más las contribuciones recibidas (impuestos trasladados - federales o locales, derechos, productos, aprovechamientos, aportaciones de seguridad social, contribuciones de mejoras) menos los impuestos retenidos y/o locales.");
        put("CFDI40120", "Cuando el valor del campo Total se encuentre fuera de los límites establecidos, debe existir el campo Confirmacion.");
        put("CFDI40121", "El campo TipoDeComprobante, no contiene un valor del catálogo c_TipoDeComprobante.");
        put("CFDI40122", "El campo Exportacion contiene el valor '02', el CFDI debe contener el complemento para Comercio Exterior.");
        put("CFDI40123", "El campo Exportacion no contiene un valor del catálogo c_Exportacion. ");
        put("CFDI40124", "El campo MetodoPago, no contiene un valor del catálogo c_MetodoPago.");
        put("CFDI40125", "Se debe omitir el campo MetodoPago cuando el TipoDeComprobante es T o P.");
        put("CFDI40126", "El campo LugarExpedicion, no contiene un valor del catálogo c_CodigoPostal.");
        put("CFDI40127", "El campo Confirmacion no debe existir cuando los campos TipoCambio y/o Total están dentro del rango permitido.");
        put("CFDI40128", "Número de confirmación inválido.");
        put("CFDI40129", "Número de confirmación utilizado previamente.");
        put("CFDI40130", "El campo Rfc del nodo receptor debe contener valor 'XAXX010101000' y el valor del campo Nombre del nodo Receptor debe contener el valor 'PUBLICO EN GENERAL'.");
        put("CFDI40131", "El campo Periodicidad, no contiene un valor del catálogo c_Periodicidad. ");
        put("CFDI40132", "El campo RegimenFiscal, no contiene el valor 621 ");
        put("CFDI40133", "El campo Meses, no contiene un valor del catálogo c_Meses. ");
        put("CFDI40134", "El campo Meses, no contiene alguno de los valores '01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11' o '12'.");
        put("CFDI40135", "El campo Meses, no contiene alguno de los valores '13', '14', '15', '16', '17' o '18'.");
        put("CFDI40136", "El campo Año, no es igual al año en curso o al año inmediato anterior.");
        put("CFDI40137", "El campo TipoRelacion, no contiene un valor del catálogo c_TipoRelacion.");
        put("CFDI40138", "El campo Nombre del emisor, debe encontrarse en la lista de RFC inscritos no cancelados en el SAT.");
        put("CFDI40139", "El campo Nombre del emisor, debe pertenecer al nombre asociado al RFC registrado en el campo Rfc del Emisor.");
        put("CFDI40140", "El campo RegimenFiscal, no contiene un valor del catálogo c_RegimenFiscal.");
        put("CFDI40141", "La clave del campo RegimenFiscal debe corresponder con el tipo de persona (fisica o moral).");
        put("CFDI40142", "El campo FacAtrAdquirente, no contiene un número de operación valido.");
        put("CFDI40143", "Este RFC del receptor no existe en la lista de RFC inscritos no cancelados del SAT.");
        put("CFDI40144", "El campo Nombre del receptor, debe encontrarse en la lista de RFC inscritos no cancelados en el SAT.");
        put("CFDI40145", "El campo Nombre del receptor, debe pertenecer al nombre asociado al RFC registrado en el campo Rfc del Receptor.");
        put("CFDI40146", "El campo RFC del receptor debe contener el valor  'XAXX010101000'.");
        put("CFDI40147", "El campo DomicilioFiscalReceptor del receptor, debe encontrarse en la lista de RFC inscritos no cancelados en el SAT.");
        put("CFDI40148", "El campo DomicilioFiscalReceptor del receptor, debe pertenecer al nombre asociado al RFC registrado en el campo Rfc del Receptor.");
        put("CFDI40149", "El campo DomicilioFiscalReceptor, no es igual al valor del campo LugarExpedicion. ");
        put("CFDI40150", "El campo ResidenciaFiscal, no contiene un valor del catálogo c_Pais.");
        put("CFDI40151", "El RFC del receptor es de un RFC registrado en el SAT o un RFC genérico nacional y existe el campo ResidenciaFiscal.");
        put("CFDI40152", "El valor del campo ResidenciaFiscal no puede ser MEX.");
        put("CFDI40153", "Se debe registrar un valor de acuerdo al catálogo c_Pais en en el campo ResidenciaFiscal, cuando en el en el campo NumRegIdTrib se registre información.");
        put("CFDI40154", "El valor del campo es un RFC inscrito no cancelado en el SAT o un RFC genérico nacional, y se registró el campo NumRegIdTrib.");
        put("CFDI40155", "Para registrar el campo NumRegIdTrib, el CFDI debe contener el complemento de comercio exterior y el RFC del receptor debe ser un RFC genérico extranjero.");
        put("CFDI40156", "El campo NumRegIdTrib no cumple con el patrón correspondiente. ");
        put("CFDI40157", "El campo RegimenFiscalR, no contiene un valor del catálogo c_RegimenFiscal.");
        put("CFDI40158", "La clave del campo RegimenFiscalR debe corresponder con el tipo de persona (física o moral).");
        put("CFDI40159", "La clave del campo RegimenFiscalR no corresponde de acuerdo al RFC del receptor.");
        put("CFDI40160", "El campo UsoCFDI, no contiene un valor del catálogo c_UsoCFDI.");
        put("CFDI40161", "La clave del campo UsoCFDI debe corresponder con el tipo de persona (física o moral) y el régimen correspondiente conforme al catálogo c_UsoCFDI.");
        put("CFDI40162", "El campo ClaveProdServ, no contiene un valor del catálogo c_ClaveProdServ.");
        put("CFDI40163", "No existe el complemento requerido para el valor de ClaveProdServ.");
        put("CFDI40164", "No está declarado el impuesto relacionado con el valor de ClaveProdServ.");
        put("CFDI40165", "El campo ClaveUnidad no contiene un valor del catálogo c_ClaveUnidad.");
        put("CFDI40166", "El valor valor del campo ValorUnitario debe ser mayor que cero (0) cuando el tipo de comprobante es Ingreso, Egreso o Nomina.");
        put("CFDI40167", "El valor del campo Importe no se encuentra entre el limite inferior y superior permitido.");
        put("CFDI40168", "El valor del campo Descuento debe tener hasta la cantidad de decimales que tenga registrado el campo importe del concepto.");
        put("CFDI40169", "El valor del campo Descuento es mayor que el campo Importe.");
        put("CFDI40170", "El campo ObjetoImp, no contiene un valor del catálogo c_ObjetoImp.");
        put("CFDI40171", "El nodo concepto, no contiene el nodo hijo Impuestos.");
        put("CFDI40172", "El nodo hijo Impuestos del nodo concepto, no debe existir.");
        put("CFDI40173", "En caso de utilizar el nodo Impuestos en un concepto, se deben incluir impuestos  de traslado y/o retenciones.");
        put("CFDI40174", "El valor del campo Base que corresponde a Traslado debe ser mayor que cero.");
        put("CFDI40175", "El valor del campo Impuesto que corresponde a Traslado no contiene un valor del catálogo c_Impuesto.");
        put("CFDI40176", "El valor del campo TipoFactor que corresponde a Traslado no contiene un valor del catálogo c_TipoFactor.");
        put("CFDI40177", "Si el valor registrado en el campo TipoFactor que corresponde a Traslado es Exento no se deben registrar los campos TasaOCuota ni Importe.");
        put("CFDI40178", "Si el valor registrado en el campo TipoFactor que corresponde a Traslado es Tasa o Cuota, se deben registrar los campos TasaOCuota e Importe.");
        put("CFDI40179", "El valor del campo TasaOCuota que corresponde a Traslado no contiene un valor del catálogo c_TasaOcuota o se encuentra fuera de rango.");
        put("CFDI40180", "El valor del campo Importe o que corresponde a Traslado no se encuentra entre el limite inferior y superior permitido.");
        put("CFDI40181", "El valor del campo Base que corresponde a Retención debe ser mayor que cero.");
        put("CFDI40182", "El valor del campo Impuesto que corresponde a Retención no contiene un valor del catálogo c_Impuesto.");
        put("CFDI40183", "El valor del campo TipoFactor que corresponde a Retención no contiene un valor del catálogo c_TipoFactor.");
        put("CFDI40184", "Si el valor registrado en el campo TipoFactor que corresponde a Retención debe ser distinto de Exento.");
        put("CFDI40185", "El valor del campo TasaOCuota que corresponde a Retención, no contiene un valor del catálogo c_TasaOcuota o se encuentra fuera de rango.");
        put("CFDI40186", "El valor del campo Importe que corresponde a Retención no se encuentra entre el limite inferior y superior permitido.");
        put("CFDI40187", "El campo ACuentaTerceros, no se encuentra en la lista l_LCO.");
        put("CFDI40188", "El valor del campo RfcACuentaTerceros, debe ser diferente de los valores de los campos Rfc del Emisor y Receptor.");
        put("CFDI40189", "El campo NombreACuentaTerceros, debe encontrarse en la lista de RFC inscritos no cancelados en el SAT.");
        put("CFDI40190", "El campo NombreACuentaTerceros, debe pertenecer al nombre asociado al RFC registrado en el campo Rfc del tercero.");
        put("CFDI40191", "El campo RegimenFiscalACuentaTerceros, no contiene un valor del catálogo c_RegimenFiscal.");
        put("CFDI40192", "El campo DomicilioFiscalACuentaTerceros, debe encontrarse en la lista de RFC inscritos no cancelados en el SAT.");
        put("CFDI40193", "El campo DomicilioFiscalACuentaTerceros, debe pertenecer al nombre asociado al RFC registrado en el campo Rfc del tercero.");
        put("CFDI40194", "El número de pedimento es inválido.");
        put("CFDI40195", "El NumeroPedimento no debe existir si se incluye el complemento de comercio exterior.");
        put("CFDI40196", "El campo ClaveProdServ, no contiene un valor del catálogo c_ClaveProdServ.");
        put("CFDI40197", "El valor del campo ValorUnitario debe ser mayor que cero (0).");
        put("CFDI40198", "El valor del campo Importe no se encuentra entre el limite inferior y superior permitido.");
        put("CFDI40199", "El número de pedimento es inválido.");
        put("CFDI40200", "El NumeroPedimento no debe existir si se incluye el complemento de comercio exterior.");
        put("CFDI40201", "Cuando el TipoDeComprobante sea T o P, el elemento Impuestos no debe existir.");
        put("CFDI40202", "El valor del campo TotalImpuestosRetenidos debe tener hasta la cantidad de decimales que soporte la moneda.");
        put("CFDI40203", "El valor del campo TotalImpuestosRetenidos debe ser igual a la suma de los importes registrados en el elemento hijo Retencion.");
        put("CFDI40204", "El valor del campo TotalImpuestosTrasladados debe tener hasta la cantidad de decimales que soporte la moneda.");
        put("CFDI40205", "El valor del campo TotalImpuestosTrasladados no es igual a la suma de los importes registrados en el elemento hijo Traslado.");
        put("CFDI40206", "Debe existir el campo TotalImpuestosRetenidos.");
        put("CFDI40207", "El campo Impuesto no contiene un valor del catálogo c_Impuesto.");
        put("CFDI40208", "Debe haber sólo un registro por cada tipo de impuesto retenido.");
        put("CFDI40209", "Debe existir el campo TotalImpuestosRetenidos.");
        put("CFDI40210", "El valor del campo Importe correspondiente a Retención debe tener hasta la cantidad de decimales que soporte la moneda.");
        put("CFDI40211", "El campo Importe correspondiente a Retención no es igual al redondeo de la suma de los importes de los impuestos retenidos registrados en los conceptos donde el impuesto sea igual al campo impuesto de este elemento.");
        put("CFDI40212", "Debe existir el campo TotalImpuestosTrasladados.");
        put("CFDI40213", "Deben exitir los campos Base, Impuesto y TipoFactor");
        put("CFDI40214", "El valor del campo Importe correspondiente a Traslado debe tener hasta la cantidad de decimales que soporte la moneda.");
        put("CFDI40215", "El campo Importe correspondiente a Traslado no es igual al redondeo de la suma de los importes de las bases trasladados registrados en los conceptos donde el impuesto del concepto sea igual al campo impuesto de este elemento y la TasaOCuota del concepto sea igual al campo TasaOCuota de este elemento.");
        put("CFDI40216", "El importe del campo Base correspondiente a Traslado no es igual al redondeo de la suma de los importes de las bases trasladados registrados en los conceptos.");
        put("CFDI40217", "El campo Impuesto no contiene un valor del catálogo c_Impuesto.");
        put("CFDI40218", "Debe haber sólo un registro con la misma combinación de impuesto, factor y tasa por cada traslado.");
        put("CFDI40219", "El valor seleccionado debe corresponder a un valor del catalogo donde la columna impuesto corresponda con el campo impuesto y la columna factor corresponda con el campo TipoFactor.");
        put("CFDI40220", "El valor del campo Importe correspondiente a Traslado debe tener hasta la cantidad de decimales que soporte la moneda.");
        put("CFDI40221", "El campo Importe correspondiente a Traslado no es igual al redondeo de la suma de los importes de los impuestos trasladados registrados en los conceptos donde el impuesto del concepto sea igual al campo impuesto de este elemento y la TasaOCuota del concepto sea igual al campo TasaOCuota de este elemento.");
        put("CFDI40999", "Error no clasificado.");

        put("CRP20101", "El valor del campo TipoDeComprobante debe ser 'P'");
        put("CRP20102", "El valor del campo Exportacion debe ser '01'");
        put("CRP20103", "El valor del campo SubTotal debe ser cero '0'.");
        put("CRP20104", "El valor del campo Moneda debe ser 'XXX'.");
        put("CRP20105", "El campo FormaPago no se debe registrar en el CFDI.");
        put("CRP20106", "El campo MetodoPago no se debe registrar en el CFDI.");
        put("CRP20107", "El campo CondicionesDePago no se debe registrar en el CFDI.");
        put("CRP20108", "El campo Descuento no se debe registrar en el CFDI.");
        put("CRP20109", "El campo TipoCambio no se debe registrar en el CFDI.");
        put("CRP20110", "El valor del campo Total debe ser cero '0'.");
        put("CRP20111", "Solo debe existir un Concepto en el CFDI. ");
        put("CRP20112", "No se deben registrar apartados dentro de Conceptos");
        put("CRP20113", "El valor del campo ClaveProdServ debe ser '84111506'.");
        put("CRP20114", "El campo NoIdentificacion no se debe registrar en el CFDI.");
        put("CRP20115", "El valor del campo Cantidad debe ser '1'.");
        put("CRP20116", "El valor del campo ClaveUnidad debe ser 'ACT'.");
        put("CRP20117", "El campo Unidad no se debe registrar en el CFDI.");
        put("CRP20118", "El valor del campo Descripcion debe ser 'Pago'.");
        put("CRP20119", "El valor del campo ValorUnitario debe ser cero '0'.");
        put("CRP20120", "El valor del campo Importe debe ser cero '0'.");
        put("CRP20121", "El campo Descuento no se debe registrar en el CFDI.");
        put("CRP20122", "El valor del campo ObjetoImp debe ser '01'.");
        put("CRP20123", "No se debe registrar el apartado de Impuestos en el CFDI.");
        put("CRP20201", "El valor del campo TotalRetencionesIVA no es igual al redondeo de la suma del resultado de multiplicar cada uno de los importes de los atributos ImporteP de los impuestos retenidos registrados en el elemento RetencionP donde el atributo ImpuestoP contenga el valor IVA por el valor registrado en el atributo TipoCambioP de cada nodo Pago.");
        put("CRP20202", "El valor del campo TotalRetencionesISR no es igual al redondeo de la suma del resultado  de multiplicar cada uno de los importes de los atributos ImporteP de los impuestos retenidos registrados en el elemento RetencionP donde el atributo ImpuestoP contenga el valor ISR por el valor registrado en el atributo TipoCambioP de cada nodo Pago.");
        put("CRP20203", "El valor del campo TotalRetencionesIEPS no es igual al redondeo de la suma del resultado de multiplicar cada uno de los importes de los atributos ImporteP de los impuestos retenidos registrados en el elemento RetencionP donde el atributo ImpuestoP contenga el valor IEPS por el valor registrado en el atributo TipoCambioP de cada nodo Pago.");
        put("CRP20204", "El valor del campo TotalTrasladosBaseIVA16 no es igual al redondeo de la suma del resultado de multiplicar cada uno de los importes de los atributos BaseP de los impuestos trasladados registrados en el elemento TrasladoP donde los atributos contengan en ImpuestoP el valor IVA, en TipoFactorP el valor Tasa y en TasaOCuotaP el valor 0.160000, por el valor registrado en el atributo TipoCambioP de cada nodo Pago.");
        put("CRP20205", "El valor del campo TotalTrasladosImpuestoIVA16 no es  igual al redondeo de la suma del resultado de multiplicar cada uno de los importes de los atributos ImporteP de los impuestos trasladados registrados en el elemento TrasladoP donde los atributos contengan en ImpuestoP el valor IVA, en TipoFactorP el valor Tasa y en TasaOCuotaP el valor 0.160000, por el valor registrado en el atributo TipoCambioP de cada nodo Pago.");
        put("CRP20206", "El valor del campo TotalTrasladosBaseIVA8 no es igual al redondeo de la suma del resultado de multiplicar cada uno de los importes de los atributos BaseP de los impuestos trasladados registrados en el elemento TrasladoP donde los atributos contengan en ImpuestoP el valor IVA, en TipoFactorP el valor Tasa y en TasaOCuotaP el valor 0.080000, por el valor registrado en el atributo TipoCambioP de cada nodo Pago.");
        put("CRP20207", "El valor del campo TotalTrasladosImpuestoIVA8 no es igual al redondeo de la suma del resultado de multiplicar  cada uno de los importes de los atributos ImporteP de los impuestos trasladados registrados en el elemento TrasladoP donde los atributos contengan en ImpuestoP el valor IVA, en TipoFactorP el valor Tasa y TasaOCuotaP el valor 0.080000, por el valor registrado en el atributo TipoCambioP de cada nodo Pago.");
        put("CRP20208", "El valor del campo TotalTrasladosBaseIVA0 no es igual al redondeo de la suma del resultado de multiplicar cada uno de los importes de los atributos BaseP de los impuestos trasladados registrados en el elemento TrasladoP donde los atributos contengan en ImpuestoP el valor IVA, en TipoFactorP el valor Tasa y en TasaOCuotaP el valor 0.000000, por el valor registrado en el atributo TipoCambioP de cada nodo Pago.");
        put("CRP20209", "El valor del campo TotalTrasladosImpuestoIVA0 no es  igual al redondeo de la suma del resultado de multiplicar cada uno de los importes de los atributos ImporteP de los impuestos trasladados registrados en el elemento TrasladoP donde los atributos contengan en ImpuestoP el valor IVA, en TipoFactorP el valor Tasa y en TasaOCuotaP el valor 0.000000, por el valor registrado en el atributo TipoCambioP de cada nodo Pago.");
        put("CRP20210", "El valor del campo TotalTrasladosBaseExento no es igual al redondeo de la suma del resultado de multiplicar cada uno de los importes de los atributos BaseP de los impuestos trasladados registrados en el elemento TrasladoP donde los atributos contengan en ImpuestoP el valor IVA y en TipoFactorP el valor Exento, por el valor registrado en el atributo TipoCambioP de cada nodo Pago.");
        put("CRP20211", "El valor del campo MontoTotalPagos no es igual al redondeo de la suma del resultado de multiplicar cada uno de los atributos Monto por el valor registrado en el atributo TipoCambioP de cada nodo Pago.");
        put("CRP20212", "El valor del campo FormaDePagoP debe ser distinto de '99'.");
        put("CRP20213", "El campo MonedaP debe ser distinto de 'XXX'");
        put("CRP20214", "El campo TipoCambioP se debe registrar. ");
        put("CRP20215", "El campo TipoCambioP debe contener el valor '1'.");
        put("CRP20216", "Cuando el valor del campo TipoCambioP se encuentre fuera de los límites establecidos, debe existir el campo Confirmacion");
        put("CRP20217", "La suma de los valores registrados en el campo ImpPagado de los apartados DoctoRelacionado no es menor o igual que el valor del campo Monto.");
        put("CRP20218", "El valor del campo Monto no es mayor que cero '0'.");
        put("CRP20219", "El valor del campo Monto debe tener hasta la cantidad de decimales que soporte la moneda registrada en el campo MonedaP.");
        put("CRP20220", "Cuando el valor del campo Monto se encuentre fuera de los límites establecidos, debe existir el campo Confirmacion");
        put("CRP20221", "El campo RfcEmisorCtaOrd no se debe registrar.");
        put("CRP20222", "El RFC del campo RfcEmisorCtaOrd no se encuentra en la lista de RFC.");
        put("CRP20223", "El campo NomBancoOrdExt se debe registrar. ");
        put("CRP20224", "El campo CtaOrdenante no se debe registrar. ");
        put("CRP20225", "El campo CtaOrdenante no cumple con el patrón requerido.");
        put("CRP20226", "El campo CtaBeneficiario no cumple con el patrón requerido.");
        put("CRP20227", "El campo RfcEmisorCtaBen no se debe registrar. ");
        put("CRP20228", "El campo CtaBeneficiario no se debe registrar. ");
        put("CRP20229", "El campo TipoCadPago no se debe registrar. ");
        put("CRP20230", "El campo CertPago se debe registrar. ");
        put("CRP20231", "El campo CertPago no se debe registrar. ");
        put("CRP20232", "El campo CadPago se debe registrar. ");
        put("CRP20233", "El campo CadPago no se debe registrar. ");
        put("CRP20234", "El campo SelloPago se debe registrar. ");
        put("CRP20235", "El campo SelloPago no se debe registrar. ");
        put("CRP20236", "El valor del campo MonedaDR debe ser distinto de 'XXX'");
        put("CRP20237", "El campo EquivalenciaDR se debe registrar. ");
        put("CRP20238", "El campo EquivalenciaDR debe contener el valor '1'. ");
        put("CRP20239", "El campo ImpSaldoAnt debe mayor a cero.");
        put("CRP20240", "El valor del campo ImpSaldoAnt debe tener hasta la cantidad de decimales que soporte la moneda registrada en el campo MonedaDR.");
        put("CRP20241", "El campo ImpPagado debe mayor a cero.");
        put("CRP20242", "El valor del campo ImpPagado debe tener hasta la cantidad de decimales que soporte la moneda registrada en el campo MonedaDR.");
        put("CRP20243", "El valor del campo ImpSaldoInsoluto debe tener hasta la cantidad de decimales que soporte la moneda registrada en el campo MonedaDR.");
        put("CRP20244", "El campo ImpSaldoInsoluto debe ser mayor o igual a cero y calcularse con la suma de los campos ImSaldoAnt menos el ImpPagado.");
        put("CRP20245", "El campo ObjetoImpDR, debe tener un valor del catálogo c_ObjetoImp.");
        put("CRP20246", "El nodo hijo ImpuestosDR del nodo DoctoRelacionado debe existir.");
        put("CRP20247", "El nodo hijo Impuestos del nodo concepto, no debe existir.");
        put("CRP20248", "En caso de utilizar el nodo Impuestos en un documento relacionado, se deben incluir impuestos  de traslados y/o retenciones.");
        put("CRP20249", "El valor del campo BaseDR que corresponde a Retención debe ser mayor que cero.");
        put("CRP20250", "El valor del campo ImpuestoDR que corresponde a Retención no contiene un valor del catálogo c_Impuesto.");
        put("CRP20251", "El valor del campo TipoFactorDR que corresponde a Retención no contiene un valor del catálogo c_TipoFactor.");
        put("CRP20252", "El valor registrado en el campo TipoFactorDR que corresponde a Retención debe ser distinto de Exento.");
        put("CRP20253", "El valor del campo TasaOCuotaDR que corresponde a Retención, no contiene un valor del catálogo c_TasaOcuota o se encuentra fuera de rango.");
        put("CRP20254", "El valor del campo ImporteDR que corresponde a Retención no se encuentra entre el limite inferior y superior permitido.");
        put("CRP20255", "El valor del campo BaseDR que corresponde a Traslado debe ser mayor que cero.");
        put("CRP20256", "El valor del campo ImpuestoDR que corresponde a Traslado no contiene un valor del catálogo c_Impuesto.");
        put("CRP20257", "El valor del campo TipoFactorDR que corresponde a Traslado no contiene un valor del catálogo c_TipoFactor.");
        put("CRP20258", "Si el valor registrado en el campo TipoFactorDR es Exento no se deben registrar los campos TasaOCuotaDR ni ImporteDR.");
        put("CRP20259", "Si el valor registrado en el campo TipoFactorDR que corresponde a Traslado es Tasa o Cuota, se deben registrar los campos TasaOCuotaDR e ImporteDR.");
        put("CRP20260", "El valor del campo TasaOCuotaDR que corresponde a Traslado no contiene un valor del catálogo c_TasaOcuota o se encuentra fuera de rango.");
        put("CRP20261", "El valor del campo ImporteDR o que corresponde a Traslado no se encuentra entre el limite inferior y superior permitido.");
        put("CRP20262", "El campo ImpuestoP no contiene un valor del catálogo c_Impuesto.");
        put("CRP20263", "Debe haber sólo un registro por cada tipo de impuesto retenido.");
        put("CRP20264", "Debe existir al menos uno de los campos TotalRetencionesIVA, TotalRetencionesISR, TotalRetencionesIEPS.");
        put("CRP20265", "El campo ImporteP  que corresponde a Retención, no es igual a la suma de los importes de los impuestos retenidos registrados en el documento relacionado donde el impuesto sea igual al campo ImpuestoP de este elemento.");
        put("CRP20266", "Deben exitir los campos BaseP, ImpuestoP y TipoFactorP");
        put("CRP20267", "Debe existir al menos uno de los campos TotalTrasladosBaseIVA16 y/o y/o TotalTrasladosBaseIVA8 y/o TotalTrasladosBaseIVA0 y/o TotalTrasladosBaseIVAExento. ");
        put("CRP20268", "El campo BaseP que corresponde a Traslado, no es igual a la suma de los importes de las bases registrados en los documentos relacionados donde el impuesto del documento relacionado sea igual al campo ImpuestoP de este elemento y la TasaOCuotaDR del documento relacionado sea igual al campo TasaOCuotaP de este elemento.");
        put("CRP20269", "El importe del campo BaseP que corresponde a Traslado, no es igual a la suma de los importes de las bases registrados en los documentos relacionados.");
        put("CRP20270", "El campo ImpuestoP que corresponde a Traslado no contiene un valor del catálogo c_Impuesto.");
        put("CRP20271", "Debe haber sólo un registro con la misma combinación de impuesto, factor y tasa por cada traslado.");
        put("CRP20272", "El valor seleccionado debe corresponder a un valor del catálogo Tasa O Cuota donde la columna impuesto corresponda con el campo ImpuestoP y la columna factor corresponda con el campo TipoFactorP.");
        put("CRP20273", "Deben existir al menos uno de los campos TotalTrasladosImpuestoIVA16, TotalTrasladosImpuestoIVA8, TotalTrasladosImpuestoIVA0 cuando existan conceptos con un TipoFactor distinto a Exento. ");
        put("CRP20274", "El campo ImporteP que corresponde a Traslado, no es igual a la suma de los importes de los impuestos registrados en el documento relacionado donde el impuesto del documento relacionado sea igual al campo ImpuestoP de este elemento y la TasaOCuotaP del documento relacionado sea igual al campo TasaOCuotaP de este elemento.");
        put("CRP20999", "Error no clasificado.");
    }};

    public static String getError(String codigo) {
        return getError(codigo, false);
    }

    public static String getError(String codigo, boolean buscar) {
        if (!buscar) {
            return errores.get(codigo) != null ? codigo + ". " + errores.get(codigo) : null;
        } else {
            for (Map.Entry<String, String> error : errores.entrySet()) {
                if (codigo.contains(error.getKey())) {
                    return error.getKey() + ". " + error.getValue();
                }
            }
        }

        return null;
    }
}